import {compareRecommendations,engineVersion,limitedJson,validateEngineDefinition,validateEvaluationContext,validateRecommendation} from "./engine-contract.js";
import {createEngineRepository} from "./engine-repository.js";

const hashText=async value=>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("")};
export function createEngineSdk({db,clock=()=>Date.now(),uuid=()=>crypto.randomUUID(),onError=()=>{}}={}){
 const repository=createEngineRepository(db);
 const report=(code,error)=>{try{onError(code,error)}catch{}}
 const register=async definition=>{validateEngineDefinition(definition);const definitionHash=await hashText(limitedJson({engineName:definition.engineName,displayName:definition.displayName,engineVersion:definition.engineVersion,ruleVersion:definition.ruleVersion,schemaVersion:definition.schemaVersion,contractVersion:definition.contractVersion,status:definition.status,enabled:definition.enabled,capabilities:definition.capabilities||[]}));try{await repository.register({...definition,definitionHash})}catch(error){report("REGISTRY_WRITE_FAILED",error);throw error}return engineVersion(definition)};
 const evaluate=async(definition,context,{strict=false}={})=>{
  validateEngineDefinition(definition);validateEvaluationContext(context);const started=clock();let value,recommendation;
  try{value=await definition.evaluate(context);recommendation=validateRecommendation(definition.toRecommendation(value))}catch(error){report("EVALUATION_FAILED",error);throw error}
  const warnings=[];try{await register(definition)}catch(error){if(strict)throw error;warnings.push("REGISTRY_WRITE_FAILED");return {ok:true,value,recommendation,executionId:null,coreRecorded:false,warnings}}
  const errorCode=recommendation.errorCode||null,operationPart=context.eventType==="MANUAL_REQUEST"?`:${context.operationId||"NO_OPERATION"}`:"",idempotencyKey=`${context.entityType}:${context.entityId}:${context.entityRevision??"NULL"}:${context.eventType}:${context.inputHash}${operationPart}`;let record;
  try{record=await repository.append({executionId:uuid(),...engineVersion(definition),entityType:context.entityType,entityId:context.entityId,siteId:context.siteId,entityRevision:context.entityRevision??null,eventType:context.eventType,inputHash:context.inputHash,result:{code:recommendation.code,confidence:Number(recommendation.confidence),reasonCodes:recommendation.reasonCodes.slice(0,20),ruleIds:recommendation.ruleIds.slice(0,50),candidateCodes:(recommendation.candidateCodes||[]).slice(0,20),requiresReview:Boolean(recommendation.requiresReview)},success:recommendation.success!==false&&!errorCode,requiresReview:Boolean(recommendation.requiresReview),conflict:Boolean(recommendation.conflict),actorUserId:context.actorUserId||null,operationId:context.operationId||null,idempotencyKey,errorCode,durationMs:Math.max(0,clock()-started)})}catch(error){report("HISTORY_WRITE_FAILED",error);if(strict)throw error;warnings.push("HISTORY_WRITE_FAILED");return {ok:true,value,recommendation,executionId:null,coreRecorded:false,warnings}}
  if(record.metricError){report("METRICS_WRITE_FAILED",record.metricError);if(strict)throw record.metricError;warnings.push("METRICS_WRITE_FAILED")}
  return {ok:true,value,recommendation,executionId:record.executionId,coreRecorded:warnings.length===0,warnings};
 };
 const confirm=async(definition,decision,{strict=false}={})=>{validateEngineDefinition(definition);if(!decision?.executionId||!decision.decisionCode||!decision.decidedByUserId||!await repository.execution(decision.executionId,definition.engineName))return {recorded:false,coreRecorded:false,warnings:[]};let record;try{record=await repository.appendDecision({decisionExecutionId:uuid(),...decision,engineName:definition.engineName})}catch(error){report("DECISION_LINK_FAILED",error);if(strict)throw error;return {recorded:false,executionId:decision.executionId,coreRecorded:false,warnings:["DECISION_LINK_FAILED"]}}if(!record.created)return {recorded:false,executionId:decision.executionId,idempotent:true,coreRecorded:true,warnings:[]};const warnings=[];try{await repository.increment({engineName:definition.engineName,engineVersion:definition.engineVersion,eventType:"DECISION_CONFIRMED",decisionCount:1,overrideCount:decision.manualOverride?1:0})}catch(error){report("METRICS_WRITE_FAILED",error);if(strict)throw error;warnings.push("METRICS_WRITE_FAILED")}return {recorded:true,executionId:decision.executionId,decisionExecutionId:record.executionId,coreRecorded:warnings.length===0,warnings}};
 return {register,evaluate,confirm,history:repository.history,metrics:repository.metrics,compare:compareRecommendations,version:engineVersion};
}
