import {compareRecommendations,engineVersion,limitedJson,validateEngineDefinition,validateEvaluationContext,validateRecommendation} from "./engine-contract.js";
import {createEngineRepository} from "./engine-repository.js";

const hashText=async value=>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("")};
export function createEngineSdk({db,clock=()=>Date.now(),uuid=()=>crypto.randomUUID(),onError=()=>{}}={}){
 const repository=createEngineRepository(db,{onError});
 const register=async definition=>{validateEngineDefinition(definition);const definitionHash=await hashText(limitedJson({engineName:definition.engineName,displayName:definition.displayName,engineVersion:definition.engineVersion,ruleVersion:definition.ruleVersion,schemaVersion:definition.schemaVersion,contractVersion:definition.contractVersion,status:definition.status,enabled:definition.enabled,capabilities:definition.capabilities||[]}));try{await repository.register({...definition,definitionHash})}catch(error){onError("REGISTRY_WRITE_FAILED",error);throw error}return engineVersion(definition)};
 const evaluate=async(definition,context)=>{
  validateEngineDefinition(definition);validateEvaluationContext(context);await register(definition);const started=clock();let value,recommendation,errorCode=null;
  try{value=await definition.evaluate(context);recommendation=validateRecommendation(definition.toRecommendation(value));}
  catch(error){errorCode=String(error?.message||"ENGINE_EVALUATION_FAILED").slice(0,120);throw error}
  finally{if(recommendation){errorCode=errorCode||recommendation.errorCode||null;const operationPart=context.eventType==="MANUAL_REQUEST"?`:${context.operationId||"NO_OPERATION"}`:"",idempotencyKey=`${context.entityType}:${context.entityId}:${context.entityRevision??"NULL"}:${context.eventType}:${context.inputHash}${operationPart}`;try{const record=await repository.append({executionId:uuid(),...engineVersion(definition),entityType:context.entityType,entityId:context.entityId,siteId:context.siteId,entityRevision:context.entityRevision??null,eventType:context.eventType,inputHash:context.inputHash,result:{code:recommendation.code,confidence:Number(recommendation.confidence),reasonCodes:recommendation.reasonCodes.slice(0,20),ruleIds:recommendation.ruleIds.slice(0,50),candidateCodes:(recommendation.candidateCodes||[]).slice(0,20),requiresReview:Boolean(recommendation.requiresReview)},success:recommendation.success!==false&&!errorCode,requiresReview:Boolean(recommendation.requiresReview),conflict:Boolean(recommendation.conflict),actorUserId:context.actorUserId||null,operationId:context.operationId||null,idempotencyKey,errorCode,durationMs:Math.max(0,clock()-started)});context.executionId=record.executionId}catch(error){onError("HISTORY_WRITE_FAILED",error);throw error}}}
  return {value,recommendation,executionId:context.executionId};
 };
 const confirm=async(definition,decision)=>{validateEngineDefinition(definition);if(!decision?.executionId||!decision.decisionCode||!decision.decidedByUserId||!await repository.execution(decision.executionId,definition.engineName))return {recorded:false};let record;try{record=await repository.appendDecision({decisionExecutionId:uuid(),...decision,engineName:definition.engineName})}catch(error){onError("DECISION_LINK_FAILED",error);throw error}if(!record.created)return {recorded:false,executionId:decision.executionId,idempotent:true};try{await repository.increment({engineName:definition.engineName,engineVersion:definition.engineVersion,eventType:"DECISION_CONFIRMED",decisionCount:1,overrideCount:decision.manualOverride?1:0})}catch(error){onError("METRICS_WRITE_FAILED",error)}return {recorded:true,executionId:decision.executionId,decisionExecutionId:record.executionId}};
 return {register,evaluate,confirm,history:repository.history,metrics:repository.metrics,compare:compareRecommendations,version:engineVersion};
}
