import { state, loadLocal, saveLocal } from "./state.js";
import { loadSettings, saveSettings } from "../services/settings.js";
import { loginSite, getSiteBundle } from "../services/api.js";
import { renderDashboard } from "../pages/dashboard.js"; import { renderSite } from "../pages/site.js"; import { renderWeather } from "../pages/weather.js"; import { renderHealth } from "../pages/health.js"; import { renderSchedule } from "../pages/schedule.js"; import { renderGuide } from "../pages/guide.js"; import { renderDatabase } from "../pages/database.js"; import { renderBriefing } from "../pages/briefing.js"; import { renderChat } from "../pages/chat.js"; import { renderSettings } from "../pages/settings.js"; import { renderAssistant } from "../pages/assistant.js";
const pages={dashboardPage:renderDashboard,sitePage:renderSite,weatherPage:renderWeather,healthPage:renderHealth,schedulePage:renderSchedule,guidePage:renderGuide,dbPage:renderDatabase,briefingPage:renderBriefing,assistantPage:renderAssistant,chatPage:renderChat,settingsPage:renderSettings};
function showMain(){document.getElementById("loginPage").classList.remove("active");document.getElementById("homePage").classList.add("active");activateSubpage("dashboardPage");}
function activateSubpage(id){document.querySelectorAll(".subpage").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelector(`[data-page="${id}"]`)?.classList.add("active");pages[id]?.(document.getElementById(id));}
function init(){loadLocal(); saveSettings(loadSettings());document.getElementById("guestStartBtn").addEventListener("click",()=>{state.mode="guest";state.site={siteName:"게스트 현장",siteType:"임시"};saveLocal();showMain();});document.getElementById("createDemoSiteBtn").addEventListener("click",()=>{state.mode="site";state.site={siteCode:"DEMO-001",pin:"1234",siteName:"김제 샘플현장",siteType:"학교"};saveLocal();alert("샘플 현장: DEMO-001 / PIN: 1234");showMain();});document.getElementById("siteLoginBtn").addEventListener("click",async()=>{const siteCode=document.getElementById("siteCodeInput").value.trim();const pin=document.getElementById("sitePinInput").value.trim();if(!siteCode||!pin){alert("현장코드와 PIN을 입력하세요.");return;}try{const login=await loginSite(siteCode,pin);const bundle=await getSiteBundle(siteCode,pin);state.mode="site";state.site={...login.site,pin};state.siteProfile={...(bundle.profile?.payload||{}),siteCode,pin,siteName:login.site.siteName,siteType:login.site.siteType};state.schedules=(bundle.schedules||[]).map(x=>x.payload&&Object.keys(x.payload).length?x.payload:x);saveLocal();showMain();}catch(error){alert("서버 현장 접속 실패: "+error.message+"\n게스트 방식으로 임시 접속합니다.");state.mode="site";state.site={siteCode,pin,siteName:siteCode,siteType:"미지정"};saveLocal();showMain();}});document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>activateSubpage(btn.dataset.page)));}
init();
