name = "guis-arc-os-api"
main = "backend/src/index.js"
compatibility_date = "2026-07-07"

[[d1_databases]]
binding = "DB"
database_name = "guis_arc_os"
database_id = "a3401472-178f-454d-84d9-d25b7515aadb"

[vars]
APP_VERSION = "8.4.0"
APP_NAME = "GUI's Arc OS"
