import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {DatabaseSync} from "node:sqlite";
import {createEngineSdk} from "../worker/core/engine-sdk.js";
import {ENGINE_CONTRACT_VERSION,ENGINE_EVENTS,selectIssueEvent} from "../worker/core/engine-contract.js";
import {CONSTRUCTION_DEPARTMENT_ENGINE} from "../worker/modules/construction-engine-adapter.js";
import {evaluateDepartmentRules} from "../worker/modules/construction-engine.js";

const read=file=>fs.readFileSync(file,"utf8");
function database(upto=null){const db=new DatabaseSync(":memory:");for(const name of fs.readdirSync("database/migrations").filter(name=>name.endsWith(".sql")&&(!upto||name<=upto)).sort())db.exec(read(`database/migrations/${name}`));return db}
function d1(db,{failRegistry=false,failHistory=false,failMetrics=false}={}){const statement=(sql,args=[])=>({sql,args,bind(...values){return statement(sql,values)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){if(failRegistry&&sql.includes("engine_registry"))throw new Error("REGISTRY_UNAVAILABLE");if(failHistory&&sql.includes("engine_history"))throw new Error("HISTORY_UNAVAILABLE");if(failMetrics&&sql.includes("engine_metrics"))throw new Error("METRICS_UNAVAILABLE");const value=db.prepare(sql).run(...args);return {success:true,meta:{changes:Number(value.changes)}}}});return {prepare:sql=>statement(sql)}}
const definition={engineName:"TEST_ENGINE",displayName:"Test Engine",engineVersion:"1.0.0",ruleVersion:"test-rules-v1",schemaVersion:"1.0",contractVersion:ENGINE_CONTRACT_VERSION,status:"ENABLED",enabled:true,capabilities:["TEST"],evaluate:async context=>({code:context.code||"A"}),toRecommendation:value=>({code:value.code,confidence:90,reasonCodes:["RULE"],ruleIds:["rule-1"],candidateCodes:[value.code],requiresReview:false,conflict:false,engineVersion:"1.0.0"})};
const context=(extra={})=>({entityType:"ISSUE",entityId:"issue-1",siteId:"site-1",entityRevision:1,eventType:ENGINE_EVENTS.ISSUE_CREATED,inputHash:"a".repeat(64),...extra});

test("0029 creates registry append-only history atomic metrics and a nullable snapshot execution link",()=>{const db=database();for(const table of["engine_registry","engine_history","engine_metrics"])assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table));const column=db.prepare("PRAGMA table_info(issue_department_recommendations)").all().find(row=>row.name==="latest_engine_execution_id");assert.equal(column.notnull,0);assert.match(read("worker/core/engine-repository.js"),/ON CONFLICT[\s\S]*evaluation_count=engine_metrics\.evaluation_count\+excluded\.evaluation_count/);db.close()});
test("0030 completes required registry history and metrics fields without rewriting 0029",()=>{const db=database("0029_engine_core_v1.sql");db.exec("INSERT INTO engine_registry(engine_name,engine_version,contract_version,lifecycle_status,definition_hash) VALUES('LEGACY_ENGINE','1.0.0','1.0.0','ACTIVE','hash')");db.exec(read("database/migrations/0030_engine_core_v1_contract_completion.sql"));const registry=new Set(db.prepare("PRAGMA table_info(engine_registry)").all().map(row=>row.name)),history=new Set(db.prepare("PRAGMA table_info(engine_history)").all().map(row=>row.name)),metrics=new Set(db.prepare("PRAGMA table_info(engine_metrics)").all().map(row=>row.name));for(const name of["display_name","rule_version","schema_version","status","enabled"])assert.ok(registry.has(name),name);for(const name of["recommendation_json","match_score","match_level","confirmed","override","linked_execution_id","evaluated_at"])assert.ok(history.has(name),name);for(const name of["execution_count","total_execution_time_ms","last_execution_time_ms","last_evaluated_at"])assert.ok(metrics.has(name),name);assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_registry WHERE engine_name='LEGACY_ENGINE'").get().n,1);db.close()});
test("0031 backfills existing metrics without changing legacy counters",()=>{const db=database("0030_engine_core_v1_contract_completion.sql");db.exec("INSERT INTO engine_registry(engine_name,engine_version,contract_version,lifecycle_status,definition_hash) VALUES('LEGACY_ENGINE','1.0.0','1.0.0','ACTIVE','hash'); INSERT INTO engine_metrics(engine_name,engine_version,metric_date,event_type,evaluation_count,success_count,duration_ms_total) VALUES('LEGACY_ENGINE','1.0.0','2026-08-02','MANUAL_REQUEST',2,2,8)");db.exec(read("database/migrations/0031_engine_core_v1_metrics_backfill.sql"));const metric=db.prepare("SELECT * FROM engine_metrics").get();assert.equal(metric.evaluation_count,2);assert.equal(metric.execution_count,2);assert.equal(metric.total_execution_time_ms,8);assert.equal(metric.last_execution_time_ms,4);db.close()});
test("0029 upgrades the current 0028 schema without changing existing issues or snapshots",()=>{const db=database("0028_internal_test_site.sql");db.exec("INSERT INTO companies(id,name) VALUES('company-1','Company'); INSERT INTO sites(id,company_id,name) VALUES('site-1','company-1','Site'); INSERT INTO users(id,login_identifier,display_name,credential_hash,credential_salt,credential_iterations) VALUES('user-1','user-1','User','hash','salt',100000); INSERT INTO issue_items(id,site_id,created_by_user_id,created_by_name_snapshot,title,location_text,description,category_code) VALUES('issue-1','site-1','user-1','User','Title','Location','Description','CONSTRUCTION'); INSERT INTO issue_department_recommendations(issue_id,site_id,recommended_department_code,confidence,confidence_label,input_hash) VALUES('issue-1','site-1','CONSTRUCTION',90,'HIGH','hash');");db.exec(read("database/migrations/0029_engine_core_v1.sql"));assert.equal(db.prepare("SELECT recommended_department_code code FROM issue_department_recommendations WHERE issue_id='issue-1'").get().code,"CONSTRUCTION");assert.equal(db.prepare("SELECT COUNT(*) n FROM issue_items").get().n,1);assert.ok(db.prepare("PRAGMA table_info(issue_department_recommendations)").all().some(row=>row.name==="latest_engine_execution_id"));db.close()});
test("SDK registers evaluates records history and increments metrics once per idempotency key",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db),clock:(()=>{let n=100;return()=>n++})(),uuid:(()=>{let n=0;return()=>`execution-${++n}`})()});const first=await sdk.evaluate(definition,context()),second=await sdk.evaluate(definition,context());assert.equal(first.executionId,"execution-1");assert.equal(second.executionId,"execution-1");assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history").get().n,1);const metric=db.prepare("SELECT * FROM engine_metrics WHERE engine_name='TEST_ENGINE'").get();assert.equal(metric.evaluation_count,1);assert.equal(metric.success_count,1);db.close()});
test("manual operations are idempotent per operation ID but distinct requests remain distinct",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db)});await sdk.evaluate(definition,context({eventType:ENGINE_EVENTS.MANUAL_REQUEST,operationId:"op-1"}));await sdk.evaluate(definition,context({eventType:ENGINE_EVENTS.MANUAL_REQUEST,operationId:"op-1"}));await sdk.evaluate(definition,context({eventType:ENGINE_EVENTS.MANUAL_REQUEST,operationId:"op-2"}));assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history").get().n,2);db.close()});
test("decision links a specific execution and an identical retry does not duplicate history or metrics",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db)}),evaluation=await sdk.evaluate(definition,context()),decision={executionId:evaluation.executionId,manualOverride:true,decisionCode:"B",decidedByUserId:"user-1",operationId:"decision-op"};db.exec("INSERT OR IGNORE INTO users(id,login_identifier,display_name,credential_hash,credential_salt,credential_iterations) VALUES('user-1','user-1','User','hash','salt',100000)");assert.equal((await sdk.confirm(definition,decision)).recorded,true);assert.equal((await sdk.confirm(definition,decision)).idempotent,true);assert.equal((await sdk.confirm(definition,{executionId:"missing",decisionCode:"B",decidedByUserId:"user-1"})).recorded,false);assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history WHERE event_type='DECISION_CONFIRMED'").get().n,1);const metric=db.prepare("SELECT * FROM engine_metrics WHERE event_type='DECISION_CONFIRMED'").get();assert.equal(metric.decision_count,1);assert.equal(metric.override_count,1);db.close()});
test("decision link failure is fail-open and preserves the existing execution",async()=>{const db=database(),evaluation=await createEngineSdk({db:d1(db)}).evaluate(definition,context());db.exec("INSERT OR IGNORE INTO users(id,login_identifier,display_name,credential_hash,credential_salt,credential_iterations) VALUES('user-1','user-1','User','hash','salt',100000)");const result=await createEngineSdk({db:d1(db,{failHistory:true})}).confirm(definition,{executionId:evaluation.executionId,manualOverride:false,decisionCode:"A",decidedByUserId:"user-1"});assert.equal(result.recorded,false);assert.equal(result.executionId,evaluation.executionId);assert.deepEqual(result.warnings,["DECISION_LINK_FAILED"]);assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history WHERE event_type='DECISION_CONFIRMED'").get().n,0);db.close()});
test("metrics storage failure preserves the execution result and history link",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db,{failMetrics:true}),uuid:()=>"execution-metrics-failure"}),evaluation=await sdk.evaluate(definition,context());assert.equal(evaluation.executionId,"execution-metrics-failure");assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history").get().n,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_metrics").get().n,0);db.close()});
test("fail-open evaluates exactly once across registry history and metrics recording failures",async()=>{for(const failure of [null,"failRegistry","failHistory","failMetrics"]){const db=database();let calls=0;const instrumented={...definition,evaluate:async input=>{calls++;return definition.evaluate(input)}},sdk=createEngineSdk({db:d1(db,failure?{[failure]:true}:{}),uuid:()=>`execution-${failure||"normal"}`}),result=await sdk.evaluate(instrumented,context());assert.equal(calls,1,failure||"normal");assert.equal(result.ok,true);assert.equal(result.value.code,"A");assert.deepEqual(result.warnings,failure?[{failRegistry:"REGISTRY_WRITE_FAILED",failHistory:"HISTORY_WRITE_FAILED",failMetrics:"METRICS_WRITE_FAILED"}[failure]]:[]);assert.equal(result.coreRecorded,!failure);assert.equal(result.executionId,failure&&failure!=="failMetrics"?null:`execution-${failure||"normal"}`);if(failure==="failHistory")assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_metrics").get().n,0);db.close()}});
test("strict mode propagates each recording failure without re-evaluation",async()=>{for(const failure of ["failRegistry","failHistory","failMetrics"]){const db=database();let calls=0;const instrumented={...definition,evaluate:async input=>{calls++;return definition.evaluate(input)}},sdk=createEngineSdk({db:d1(db,{[failure]:true})});await assert.rejects(()=>sdk.evaluate(instrumented,context(),{strict:true}));assert.equal(calls,1,failure);db.close()}});
test("manual retry evaluates once per call while history and metrics remain idempotent",async()=>{const db=database();let calls=0;const instrumented={...definition,evaluate:async input=>{calls++;return definition.evaluate(input)}},sdk=createEngineSdk({db:d1(db)}),manual=context({eventType:ENGINE_EVENTS.MANUAL_REQUEST,operationId:"manual-stable"});await sdk.evaluate(instrumented,manual);await sdk.evaluate(instrumented,manual);assert.equal(calls,2);assert.equal(db.prepare("SELECT COUNT(*) n FROM engine_history").get().n,1);assert.equal(db.prepare("SELECT evaluation_count n FROM engine_metrics WHERE event_type='MANUAL_REQUEST'").get().n,1);db.close()});
test("SDK exposes history metrics compare version and rejects a changed registered definition",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db)});await sdk.evaluate(definition,context());assert.equal((await sdk.history({engineName:"TEST_ENGINE",entityId:"issue-1"})).length,1);assert.equal((await sdk.metrics({engineName:"TEST_ENGINE",engineVersion:"1.0.0"})).length,1);assert.deepEqual(sdk.version(definition),{engineName:"TEST_ENGINE",engineVersion:"1.0.0",ruleVersion:"test-rules-v1",schemaVersion:"1.0",contractVersion:"1.0.0"});assert.equal(sdk.compare({code:"A",confidence:80},{code:"B",confidence:90}).confidenceDelta,10);await assert.rejects(()=>sdk.register({...definition,capabilities:["CHANGED"]}),/ENGINE_REGISTRY_DEFINITION_CONFLICT/);db.close()});
test("Context accepts null revision and future event strings while rejecting missing required fields",async()=>{const db=database(),sdk=createEngineSdk({db:d1(db)});const evaluated=await sdk.evaluate(definition,context({entityRevision:null,eventType:"FUTURE_ENGINE_EVENT"}));assert.ok(evaluated.executionId);assert.equal(db.prepare("SELECT entity_revision FROM engine_history").get().entity_revision,null);await assert.rejects(()=>sdk.evaluate(definition,context({entityId:""})),/ENGINE_ENTITYID_REQUIRED/);db.close()});
test("Constitution contains all ten named contracts",()=>{const doc=read("docs/38_ENGINE_CONSTITUTION_V1.md");for(const name of["Input Contract","Recommendation Contract","Decision Contract","History Contract","Metrics Contract","Version Contract","Event Contract","Audit Contract","Override Contract","Lifecycle Contract"])assert.match(doc,new RegExp(name))});
test("event precedence produces one deterministic evaluation reason",()=>{assert.equal(selectIssueEvent({titleChanged:true,descriptionChanged:true,tradeChanged:true}),ENGINE_EVENTS.TRADE_CHANGED);assert.equal(selectIssueEvent({titleChanged:true,descriptionChanged:true}),ENGINE_EVENTS.DESCRIPTION_CHANGED);assert.equal(selectIssueEvent({titleChanged:true}),ENGINE_EVENTS.TITLE_CHANGED);assert.equal(selectIssueEvent({}),null)});
test("Construction adapter is a golden parity mapping over the unchanged evaluator",()=>{const rules=[{id:"rule",site_id:null,department_code:"SAFETY",rule_name:"safety",include_keywords_json:'["guard"]',exclude_keywords_json:"[]",trade_id:null,priority:900,base_confidence:95,source:"SYSTEM",is_active:1}],legacy=evaluateDepartmentRules({description:"guard"},rules),adapted=CONSTRUCTION_DEPARTMENT_ENGINE.toRecommendation(legacy);assert.equal(adapted.code,legacy.departmentCode);assert.equal(adapted.confidence,legacy.confidence);assert.deepEqual(adapted.ruleIds,legacy.ruleIds)});
test("Core integration is feature flagged and the adapter never re-evaluates after recording failure",()=>{const source=read("worker/modules/issues.js");assert.match(source,/env\.ENGINE_CORE_ENABLED==="true"/);assert.doesNotMatch(source,/catch\{\}\}if\(!result\)result=await recommendIssueDepartment/);assert.match(source,/else result=await recommendIssueDepartment/);assert.match(read("worker/modules/construction-engine.js"),/COALESCE\(excluded\.latest_engine_execution_id/);assert.doesNotMatch(source,/departmentRecommendation:[\s\S]{0,500}executionId/)});
test("Integration enables Core explicitly while an absent flag remains disabled and Production is untouched",()=>{assert.match(read("wrangler.integration.toml"),/ENGINE_CORE_ENABLED = "true"/);assert.doesNotMatch(read("wrangler.pages.toml"),/ENGINE_CORE_ENABLED/);assert.match(read("worker/modules/issues.js"),/env\.ENGINE_CORE_ENABLED==="true"/)});
test("history stores bounded result JSON and never raw normalized input",()=>{const migration=read("database/migrations/0029_engine_core_v1.sql"),repository=read("worker/core/engine-repository.js");assert.match(migration,/CHECK\(length\(result_json\)<=8192\)/);assert.doesNotMatch(migration,/raw_input|normalized_input/);assert.doesNotMatch(repository,/normalizedInput/)});
