import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import {DatabaseSync} from"node:sqlite";
const read=file=>fs.readFileSync(file,"utf8"),migration=read("database/migrations/0011_onboarding_board_access.sql"),api=read("worker/modules/integrated-admin.js"),ui=read("apps/web/assets/integrated-admin.js"),join=read("apps/web/assets/public-invite.js"),format=read("apps/web/assets/format.js");
const pinPolicy=read("worker/core/pin-policy.js");
function database(){const db=new DatabaseSync(":memory:");for(const name of fs.readdirSync("database/migrations").sort())db.exec(read(`database/migrations/${name}`));return db}
test("onboarding and hierarchy migrations preserve identity and expand canonical trades",()=>{const db=database(),companyColumns=db.prepare("PRAGMA table_info(companies)").all().map(x=>x.name),membershipColumns=db.prepare("PRAGMA table_info(memberships)").all().map(x=>x.name);assert.ok(companyColumns.includes("business_registration_number"));assert.ok(membershipColumns.includes("approval_status"));assert.ok(db.prepare("SELECT COUNT(*) count FROM trade_master WHERE status='ACTIVE'").get().count>400);assert.equal(db.prepare("SELECT COUNT(*) count FROM trade_categories").get().count,14);assert.equal(db.prepare("SELECT COUNT(*) count FROM trade_master WHERE id IN ('trade-rebar','trade-formwork','trade-concrete','trade-waterproof') AND group_id IS NOT NULL").get().count,4);assert.ok(db.prepare("SELECT 1 FROM board_definitions WHERE board_key='WORKFORCE_DAILY_OUTPUT' AND is_active=1").get());assert.match(db.prepare("SELECT sql FROM sqlite_master WHERE name='idx_companies_business_registration_number'").get().sql,/UNIQUE INDEX/);db.close()});
test("company and site contract APIs validate canonical standard trades and audit",()=>{for(const token of["authenticate(request,env,{csrf:write})","CONTEXT_VERSION_STALE","COMPANY_CREATED","SITE_COMPANY_CONNECTED","business_registration_number","company_trades","trade_master","CONTRACT_TRADE_SCOPE_INVALID"])assert.ok(api.includes(token));assert.match(api,/company_site_contract_trades/);assert.doesNotMatch(api,/credential_hash.*json|json.*credential_hash/i)});
test("company create API and UI expose field-specific Korean validation",()=>{for(const token of["COMPANY_NAME_REQUIRED","COMPANY_NAME_TOO_LONG","COMPANY_TYPE_REQUIRED","COMPANY_TYPE_INVALID","BUSINESS_NUMBER_REQUIRED","BUSINESS_NUMBER_INVALID_LENGTH","BUSINESS_NUMBER_INVALID_FORMAT","BUSINESS_NUMBER_DUPLICATE","COMPANY_TRADES_REQUIRED","COMPANY_TRADE_INVALID"])assert.ok(api.includes(token));for(const token of["company-error-summary","현재 ${number.length}자리입니다","focusFirstCompanyError","scrollIntoView","회사명을 입력해 주세요.","표준 공종을 하나 이상 선택해 주세요."])assert.ok(ui.includes(token));assert.match(read("worker/index.js"),/field.*details/);});
test("invitation acceptance reuses the strong four digit PIN policy, preserves existing users and is single use",()=>{for(const token of["invitation_acceptances","SELECT id FROM users WHERE login_identifier","INSERT OR IGNORE INTO memberships","INSERT OR IGNORE INTO user_site_roles","INVITATION_ALREADY_USED","deriveCredential","pinValidationError"])assert.ok(api.includes(token));for(const token of["^[0-9]{4}$","단순 PIN","step"])assert.ok(pinPolicy.includes(token));assert.match(api,/approval_status/);assert.doesNotMatch(api,/metadata.*pin|metadata.*credential/i)});
test("invitation creation permits an optional team without treating omission as invalid",()=>{assert.match(api,/teamId=body\.teamId\?clean\(body\.teamId,80\):null/);assert.doesNotMatch(api,/teamId=clean\(body\.teamId,80\)/)});
test("administration provides invitation copy, canonical trade and four digit PIN onboarding",()=>{for(const token of["navigator.clipboard","tradeId","site-contracts","회사","공종"])assert.ok(ui.includes(token));for(const token of["formatPhone","formatBusinessNumber","canonicalPhone","canonicalBusinessNumber"])assert.ok(format.includes(token));for(const token of["아이디","readonly","pattern=\"[0-9]{4}\"","PIN","승인"])assert.ok(join.includes(token))});
test("expired, cancelled and accepted invitations expose no reusable copy or cancel action",()=>{assert.match(ui,/x\.effectiveStatus==="PENDING"\?x\.display_code/);assert.match(ui,/x\.effectiveStatus==="PENDING"\?`<button/);assert.doesNotMatch(ui,/x\.status==="PENDING"\?x\.display_code/)});
test("role editing is separate from board access and master assignment stays restricted",()=>{assert.match(api,/assigningMaster/);assert.match(api,/USER_ADMIN_SCOPE_DENIED/);assert.match(ui,/actorMaster/);assert.match(ui,/INTEGRATED_OWNER/);assert.doesNotMatch(api,/UPDATE module_entitlements/);assert.match(read("worker/core/session.js"),/visibleModulesFromBoards/)});
test("pending memberships require explicit audited approval before board modules appear",()=>{const session=read("worker/core/session.js");assert.match(api,/\["APPROVED","REJECTED"\]/);assert.match(api,/MEMBERSHIP_\$\{approvalStatus\}/);assert.match(api,/approvalStatus/);assert.match(ui,/가입 승인/);assert.match(session,/approval_status==="APPROVED"/)});
test("master user management atomically changes site company and compatible role",()=>{for(const token of["updateUserMembership","masterOnly:true","USER_COMPANY_SCOPE_INVALID","USER_ROLE_SCOPE_DENIED","USER_MEMBERSHIP_UPDATED","UPDATE memberships SET status='INACTIVE'","UPDATE workforce_site_enrollments SET company_id","context_version=context_version+1"])assert.ok(api.includes(token));for(const token of["소속 회사","현장 역할·직급","소속·역할 저장","user-membership-form","/membership"])assert.ok(ui.includes(token));assert.match(api,/company_site_contracts/);assert.match(api,/ROLE_COMPATIBILITY\[company\.company_type\]/)});
test("invited and role-edited Safety users receive missing board grants",()=>{const repair=read("database/migrations/0019_safety_invited_role_access.sql");for(const token of["safetyGrantStatements","SAFETY_CORRECTIVE_ACTION","module_entitlements"])assert.ok(api.includes(token));for(const token of["CONTRACTOR_SITE_MANAGER","board_access_grants","SAFETY_CASE","SAFETY_CORRECTIVE_ACTION","context_version"])assert.ok(repair.includes(token))});

test("master-only site creation is atomic, assigns site manager access and switches through context API",()=>{for(const token of["/api/v1/admin/sites","masterOnly:true","SITE_COMPANY_NOT_FOUND","SITE_NAME_REQUIRED","SITE_NAME_DUPLICATE","INSERT INTO sites","approval_status","SITE_MANAGER","SITE_CREATED","defaultBoardGrantStatements","context_version=context_version+1"])assert.ok(api.includes(token));assert.match(api,/env\.DB\.batch\(statements\)/);assert.match(api,/lower\(trim\(name\)\)=lower\(\?2\)/);for(const token of["/admin/sites","새 현장 만들기","현장이 생성되었습니다","/api/v1/context/site","location.replace(\"/today\")"])assert.ok(ui.includes(token));assert.match(read("worker/index.js"),/memberships m JOIN sites s/);});
test("site creation remains master-only and does not use provisioning",()=>{const start=api.indexOf("async function createSite"),end=api.indexOf("async function tradeOptions"),siteBlock=api.slice(start,end);assert.ok(start>=0&&end>start);assert.match(siteBlock,/masterOnly:true/);assert.match(siteBlock,/roleCode:\"SITE_MANAGER\"/);assert.doesNotMatch(siteBlock,/PROVISIONING|roleCode:\"PLATFORM_OWNER\"|roleCode:\"INTEGRATED_OWNER\"/);});
test("site creation keeps active sessions aligned for immediate context switching",()=>{const start=api.indexOf("async function createSite"),end=api.indexOf("async function tradeOptions"),siteBlock=api.slice(start,end);assert.match(siteBlock,/UPDATE users SET context_version=context_version\+1/);assert.match(siteBlock,/UPDATE sessions SET context_version=context_version\+1 WHERE user_id=\?1 AND revoked_at IS NULL/);assert.match(ui,/\/api\/v1\/context\/site/);});