import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import {DatabaseSync} from"node:sqlite";import {canIssueTransition,ISSUE_STATUSES} from"../worker/modules/issues.js";
const read=file=>fs.readFileSync(file,"utf8"),migration=read("database/migrations/0002_issue_foundation.sql"),worker=read("worker/modules/issues.js"),ui=read("apps/web/assets/issues.js"),sw=read("apps/web/service-worker.js");
function database(){const db=new DatabaseSync(":memory:");db.exec(read("database/migrations/0001_core_foundation.sql"));db.exec("INSERT INTO roles(id,code,name,rank) VALUES('role-owner','INTEGRATED_OWNER','Owner',1000)");db.exec(migration);return db}
test("Issue migration creates owned tables, foreign keys, and indexes",()=>{const db=database(),tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(v=>v.name),indexes=db.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().map(v=>v.name);for(const name of["issue_items","issue_assignments","issue_actions","issue_media","issue_status_history","issue_completion_requests","issue_comments","issue_idempotency"])assert.ok(tables.includes(name));for(const name of["idx_issue_items_site_status_created","idx_issue_items_site_assignee_status","idx_issue_items_site_trade_status","idx_issue_actions_issue_created","idx_issue_history_issue_created"])assert.ok(indexes.includes(name));assert.equal(db.prepare("PRAGMA foreign_keys").get().foreign_keys,1)});
test("Issue permission catalog has eleven reusable permissions",()=>{const db=database();assert.equal(db.prepare("SELECT COUNT(*) AS count FROM permissions WHERE module_code='issue'").get().count,11);assert.equal(db.prepare("SELECT COUNT(*) AS count FROM role_permissions WHERE role_id='role-owner'").get().count,11)});
test("canonical state machine blocks shortcuts and supports rework",()=>{assert.deepEqual(ISSUE_STATUSES,["OPEN","ASSIGNED","ACTION_IN_PROGRESS","COMPLETION_REQUESTED","COMPLETED","REWORK_REQUIRED","CANCELLED"]);assert.equal(canIssueTransition("OPEN","COMPLETED"),false);assert.equal(canIssueTransition("OPEN","ASSIGNED"),true);assert.equal(canIssueTransition("ACTION_IN_PROGRESS","COMPLETION_REQUESTED"),true);assert.equal(canIssueTransition("COMPLETION_REQUESTED","REWORK_REQUIRED"),true);assert.equal(canIssueTransition("REWORK_REQUIRED","ACTION_IN_PROGRESS"),true);assert.equal(canIssueTransition("COMPLETED","OPEN"),false)});
test("Issue API contracts enforce session, CSRF, board access, business scope, revision, audit and idempotency",()=>{for(const token of["authenticate(request,env,{csrf:write})","x-context-version","CONTEXT_VERSION_STALE","requireBoardAccess","SITE_CONTEXT_MISMATCH","ISSUE_RECORD_SCOPE_DENIED","ISSUE_STALE_REVISION","idempotency-key","auditStatement","issue_status_history"])assert.ok(worker.includes(token));assert.doesNotMatch(worker,/ISSUE_PERMISSION_DENIED/);assert.match(ui,/currentCsrf/);assert.match(ui,/document\.cookie/);for(const route of["/api/v1/issues","request-completion","confirm-completion","rework","cancel","media/thumbnail"])assert.ok(worker.includes(route))});
test("completion request requires action photo and R2 failure cleans objects",()=>{assert.match(worker,/ISSUE_ACTION_PHOTO_REQUIRED/);assert.match(worker,/media\.cleanup\(\)/);assert.match(worker,/sites\/\$\{siteId\}\/issues/);assert.ok(!migration.match(/BLOB/i))});
test("Issue UI is shared-shell, paginated, photo-first and responsive",()=>{for(const token of["pageSize","loading=\"lazy\"","makeThumbnail","idempotency-key","/issues/summary","/issues/options","navigator.onLine","OFFLINE"])assert.ok((ui+sw).includes(token));const css=read("apps/web/assets/issues.css");for(const token of["issue-grid","issue-form","@media(max-width:760px)","min-height:44px"])assert.ok(css.includes(token))});
test("shared PWA uses v0.24.11 cache, network-first navigation and blocks offline final actions",()=>{const manifest=JSON.parse(read("apps/web/manifest.webmanifest"));assert.equal(manifest.name,"GUI's Arc Integrated");assert.equal(manifest.display,"standalone");assert.match(sw,/guis-arc-integrated-v0\.24\.11(?:-r\d+)?-shell/);assert.match(sw,/event\.request\.mode==="navigate"/);assert.match(sw,/url\.pathname\.startsWith\("\/api\/"\)/);assert.match(sw,/OFFLINE_FINAL_ACTION_BLOCKED/);assert.doesNotMatch(sw,/skipWaiting/)});
test("legacy Issue remains reference-only",()=>{const docs=read("docs/02_MODULE_BOUNDARIES.md")+read("docs/03_DATA_OWNERSHIP.md");assert.ok(!worker.includes("platform_users"));assert.ok(!worker.includes("Authorization Code"));assert.match(docs,/direct cross-module table mutation is forbidden/)});
