import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {applySpeechCorrections,dominantSpeechCorrection,normalizeSpeechCorrection} from "../worker/modules/speech-correction.js";

const rule=(id,value,evidence,negative=0,status=evidence>=3?"ACTIVE":"CANDIDATE",site="site-a")=>({id,site_id:site,field_type:"CONTENT_TERM",raw_normalized:"a",corrected_value:value,evidence_count:evidence,negative_evidence_count:negative,status,last_seen_at:id});
test("learned correction stays candidate before three confirmations",()=>{assert.equal(dominantSpeechCorrection([rule("1","B",1)]),null);assert.equal(dominantSpeechCorrection([rule("2","B",2)]),null)});
test("third confirmation activates an unambiguous correction",()=>{assert.equal(dominantSpeechCorrection([rule("3","B",3)])?.corrected_value,"B")});
test("conflicting candidates fall back unless one is dominant",()=>{assert.equal(dominantSpeechCorrection([rule("a","B",3),rule("b","C",2,"0","ACTIVE")]),null);assert.equal(dominantSpeechCorrection([rule("a","B",8),rule("b","C",2,0,"ACTIVE")])?.corrected_value,"B")});
test("negative evidence can suppress an active rule",()=>assert.equal(dominantSpeechCorrection([rule("a","B",3,3)]),null));
test("correction application is field-aware",()=>{const result=applySpeechCorrections("A",[rule("a","B",3)],{});assert.equal(result.content,"B");assert.deepEqual(result.appliedRuleIds,["a"])});
test("normalization is deterministic",()=>assert.equal(normalizeSpeechCorrection("  A   B  "),"a b"));
test("migration has bounded JSON, site scope, indexes, and delete-safe issue FK",()=>{const sql=fs.readFileSync(new URL("../database/migrations/0035_speech_correction_learning.sql",import.meta.url),"utf8");assert.match(sql,/speech_correction_events/);assert.match(sql,/speech_correction_rules/);assert.match(sql,/ON DELETE SET NULL/);assert.match(sql,/json_valid/);assert.match(sql,/UNIQUE\(site_id, field_type, raw_normalized, corrected_value\)/);assert.match(sql,/idx_speech_correction_rules_lookup/)});
test("location fields are optional in browser and Worker contracts",()=>{const ui=fs.readFileSync(new URL("../apps/web/assets/issues.js",import.meta.url),"utf8"),flow=ui.slice(ui.indexOf("async function createV3"),ui.indexOf("async function detail")),worker=fs.readFileSync(new URL("../worker/modules/issues.js",import.meta.url),"utf8");assert.doesNotMatch(flow,/name="building" required/);assert.doesNotMatch(flow,/unit\.required\s*=\s*true/);assert.doesNotMatch(worker,/ISSUE_BUILDING_REQUIRED/);assert.match(worker,/위치 미지정/)});
test("safe mode preserves immutable raw speech without mutating location fields",()=>{const ui=fs.readFileSync(new URL("../apps/web/assets/issues.js",import.meta.url),"utf8"),flow=ui.slice(ui.indexOf("async function createV3"),ui.indexOf("async function detail")),onresult=flow.slice(flow.indexOf("recognition.onresult"),flow.indexOf("recognition.onerror"));assert.match(onresult,/const rawTranscript=event\.results\[0\]\[0\]\.transcript/);assert.match(onresult,/description\.value=rawTranscript/);assert.match(onresult,/extractLocationSpeech\(rawTranscript/);assert.doesNotMatch(onresult,/parseSpeech\(/);assert.doesNotMatch(onresult,/addAndSelect\(/);assert.match(onresult,/위치 보조 미사용/);assert.match(onresult,/appliedRuleIds:\[\]/);assert.doesNotMatch(onresult,/applySpeechCorrections\(rawTranscript/);assert.match(flow,/speechRawTranscript/)})
