import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {spawnSync} from "node:child_process";

const root=new URL("..",import.meta.url),read=file=>fs.readFileSync(new URL(file,root),"utf8");
const expected=["guis-arc-review","guis-arc-implement","guis-arc-verify","guis-arc-deploy","guis-arc-package","guis-arc-architecture-review","guis-arc-code-review","guis-arc-bug-investigation","guis-arc-test-generator","guis-arc-browser-e2e","guis-arc-migration-data-integrity","guis-arc-security-audit","guis-arc-api-contract-validator","guis-arc-ui-ux-review","guis-arc-cloudflare-deployment"];

test("v0.24.4 keeps five orchestration skills and adds exactly ten specialist skills",()=>{const dirs=fs.readdirSync(new URL(".agents/skills",root),{withFileTypes:true}).filter(value=>value.isDirectory()).map(value=>value.name).sort();assert.deepEqual(dirs,[...expected].sort());assert.equal(new Set(dirs).size,15)});
test("all project skills have exact SKILL.md frontmatter and required sections",()=>{for(const name of expected){const dir=new URL(`.agents/skills/${name}/`,root),files=fs.readdirSync(dir),text=read(`.agents/skills/${name}/SKILL.md`);assert.ok(files.includes("SKILL.md"));assert.match(text,new RegExp(`^---\\r?\\nname: ${name}\\r?\\ndescription: .+\\r?\\n---`));for(const section of["목적","사용 조건","사용하지 않는 경우","먼저 읽을 문서","예상 문제·부작용·충돌","입력","절차","변경 허용 범위","금지사항","테스트 및 검증","완료 조건","결과 보고 형식","NOT_EXECUTED 기준"])assert.match(text,new RegExp(`^#{1,3} ${section}`,"m"));assert.doesNotMatch(text,/[A-Z]:\\Users\\|\/Users\/|\/home\//i)}});
test("skill validator is read-only and succeeds",()=>{const script=read("scripts/validate-skills.mjs");assert.doesNotMatch(script,/writeFile|rmSync|unlink|mkdirSync/);const result=spawnSync(process.execPath,["scripts/validate-skills.mjs"],{cwd:new URL(root),encoding:"utf8"});assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/Skill validation PASS: 15개/)});
test("AGENTS and development rules connect selection without duplicating skills",()=>{const agents=read("AGENTS.md"),rules=read("DEVELOPMENT_RULES.md");assert.match(agents,/\.agents\/skills/);assert.match(agents,/architecture-review.*implement 또는 bug-investigation.*code-review/);assert.match(agents,/실제로 읽은 Skill만/);assert.match(rules,/Skill 정적 검증.*실제 Codex 자동 발견 E2E/)});
test("trigger evaluation includes explicit implicit and exclusion cases for every specialist skill",()=>{const evals=read("AIOS/SKILL_EVALS.md");for(const name of expected.slice(5)){assert.ok(evals.split(name).length>=4,`${name} 사례 부족`)}for(const type of["명시","암묵","오호출 금지"])assert.match(evals,new RegExp(type));assert.match(evals,/실제 자동 발견 E2E는 `NOT_EXECUTED`/)});
test("package scripts expose skills validate without a fake automatic trigger evaluator",()=>{const pkg=JSON.parse(read("package.json"));assert.equal(pkg.scripts["skills:validate"],"node scripts/validate-skills.mjs");assert.equal(pkg.scripts["skills:eval"],undefined);assert.match(read("scripts/package-integrated.mjs"),/"\.agents"/)});
