import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";const app=fs.readFileSync("apps/web/assets/app.js","utf8"),css=fs.readFileSync("apps/web/assets/app.css","utf8"),modules=fs.readFileSync("packages/permissions/modules.js","utf8");
test("navigation order, role menu skeleton, and planned state are canonical",()=>{for(const value of["today","workforce","construction","issue","safety","quality","materials","equipment","documents","admin"])assert.ok(modules.indexOf(`code:"${value}"`)>=0);assert.match(app,/allowed\.has\(module\.code\)/);assert.match(app,/현재 준비 중인 기능입니다/);assert.match(app,/ctx\.menuModules\|\|ctx\.modules/)});
test("desktop and mobile shell preserve interaction sizes",()=>{assert.match(css,/grid-template-columns:var\(--sidebar-width\)/);assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/min-height:44px/);assert.match(css,/mobile-nav/)});
test("mobile logout has an explicit executable handler",()=>{assert.match(app,/function performLogout/);assert.match(app,/closest\?\.\("#mobile-logout"\)/);assert.match(app,/stopImmediatePropagation/);assert.match(app,/api\("\/auth\/logout"/)});


test("common mobile header replaces bottom navigation without changing desktop sidebar",()=>{assert.doesNotMatch(app,/<nav class="mobile-nav">/);assert.match(app,/mobileNavigation\(allowed\)/);assert.match(css,/\.mobile-nav\{display:none!important\}/);assert.match(css,/grid-template-columns:var\(--sidebar-width\)/);assert.match(css,/:root\{--mobile-nav-height:0px\}/)});

test("mobile site selector and menu preserve full names scroll close install and logout",()=>{for(const token of ["mobile-site-button","mobile-site-options","mobile-more-button","mobile-install","mobile-logout","/context/site"])assert.match(app,new RegExp(token));assert.match(css,/#mobile-site-button\{[^}]*text-overflow:ellipsis/);assert.match(css,/\.mobile-site-options button\{[^}]*white-space:normal/);assert.match(css,/\.mobile-site-options\{[^}]*overflow-y:auto/);assert.match(css,/\.mobile-more-scroll\{[^}]*max-height:[^;]+;overflow-y:auto/);assert.match(app,/closeMobileMenu/);assert.match(app,/beforeinstallprompt/)});
