import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import {DatabaseSync} from"node:sqlite";import {kstDate,QR_ROTATION_SECONDS,QR_TTL_SECONDS} from"../worker/modules/workforce.js";
const read=file=>fs.readFileSync(file,"utf8"),migration=read("database/migrations/0004_workforce_foundation.sql"),worker=read("worker/modules/workforce.js"),ui=read("apps/web/assets/workforce.js"),sw=read("apps/web/service-worker.js");
function database(){const db=new DatabaseSync(":memory:");for(const file of["0001_core_foundation.sql","0002_issue_foundation.sql","0003_issue_operational_stabilization.sql","0004_workforce_foundation.sql"])db.exec(read(`database/migrations/${file}`));return db}
test("Workforce migration creates owned tables, constraints and indexes",()=>{const db=database(),tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(v=>v.name),indexes=db.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().map(v=>v.name);for(const name of["workforce_profiles","workforce_site_enrollments","workforce_devices","workforce_qr_sessions","workforce_attendance","workforce_attendance_events","workforce_idempotency"])assert.ok(tables.includes(name));for(const name of["idx_workforce_attendance_status","idx_workforce_attendance_company","idx_workforce_attendance_trade","idx_workforce_qr_expiry","idx_workforce_devices_status"])assert.ok(indexes.includes(name));assert.match(migration,/UNIQUE\(user_id,site_id,work_date\)/)});
test("Workforce board access preserves site and self-only data boundaries",()=>{const db=database();assert.equal(db.prepare("SELECT COUNT(*) count FROM permissions WHERE module_code='workforce'").get().count,11);assert.equal(db.prepare("SELECT COUNT(*) count FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.code='FIELD_WORKER' AND p.module_code='workforce'").get().count,3);assert.match(worker,/ctx\.selectedSiteId/);assert.match(worker,/requireBoardAccess/);assert.doesNotMatch(worker,/WORKFORCE_PERMISSION_DENIED/)});
test("dynamic QR is signed, site-bound, short-lived and fail-closed",()=>{assert.equal(QR_ROTATION_SECONDS,60);assert.equal(QR_TTL_SECONDS,90);for(const token of["HMAC","SHA-256","WORKFORCE_QR_SECRET_MISSING","QR_TAMPERED","QR_FUTURE_ISSUED","QR_EXPIRED","QR_WRONG_SITE","qr_token_hash"])assert.ok(worker.includes(token));assert.ok(!migration.includes("signing_secret"));assert.ok(!migration.includes("qr_payload"))});
test("attendance is KST, idempotent, audited and contains no GPS",()=>{assert.equal(kstDate(new Date("2026-07-21T15:30:00Z")),"2026-07-22");for(const token of["idempotency-key","IDEMPOTENCY_PAYLOAD_MISMATCH","WORKFORCE_DUPLICATE_CHECK_IN","workforce_attendance_events"])assert.ok(worker.includes(token));assert.doesNotMatch(worker,/latitude|longitude|geolocation/i)});
test("Workforce UI renders a real QR and never claims offline check-in",()=>{for(const token of["/qr/current","/check-in","duplicate","QRCode.toCanvas","BarcodeDetector","카메라"])assert.ok(ui.includes(token));assert.match(sw,/OFFLINE_FINAL_ACTION_BLOCKED/);assert.match(read("apps/web/assets/workforce.css"),/@media\(max-width:760px\)/)});
test("Today Workforce provider is real and isolated",()=>{const provider=read("worker/modules/today/providers/workforce-provider.js"),service=read("worker/modules/today/today-service.js");assert.match(provider,/implementationStatus:"IMPLEMENTED"/);assert.match(provider,/workforce_attendance/);assert.match(service,/try[\s\S]*catch/)});
