import { todayYmd } from "../services/workInstanceDatabase.js";
import { addConstructionDrawing, addConstructionHandover, constructionWorkForDate, ensureConstructionState, saveConstructionRecord, toggleConstructionDrawing, toggleConstructionTaskItem, saveConstructionInspection } from "../services/constructionManagement.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const statusButton=(value,current)=>`<button type="button" class="construction-quick-status ${current===value?"active":""}" data-status="${value}">${value}</button>`;
function card(work){
 const items=work.constructionTasks.flatMap(task=>(task.items||[]).map((item,index)=>({task,item,index,checked:Boolean(task.checkedItems?.[index])})));
 const done=items.filter(x=>x.checked).length,r=work.record||{},inspection=work.inspection||{status:"미요청"};
 const ready=[Boolean(r.workPlanConfirmed),Boolean(r.prerequisitesConfirmed),inspection.status==="검측완료",r.status==="완료"].filter(Boolean).length;
 return `<article class="construction-work-card simple-construction-card" data-work-id="${esc(work.workId)}">
 <header class="construction-work-head"><div><span class="work-id-chip">공사작업</span><h3>${esc(work.subProcess||work.title)}</h3><p>${esc(work.location||"위치 미입력")} · ${esc(work.contractor||"협력업체 미입력")}</p></div><span class="construction-progress">준비 ${ready}/4</span></header>
 <section class="construction-action-strip"><div><b>현재 상태</b><span>${esc(r.status||"확인")}</span></div><div class="construction-status-buttons">${["확인","진행","완료"].map(x=>statusButton(x,r.status||"확인")).join("")}</div></section>
 <div class="construction-simple-grid">
  <section class="construction-step-card"><div class="step-no">1</div><div><h4>작업계획 확인</h4><p>작업순서·방법·인원·장비·안전조치를 확인합니다.</p></div><label class="big-check"><input class="work-plan-confirm" type="checkbox" ${r.workPlanConfirmed?"checked":""}><span>${r.workPlanConfirmed?"확인완료":"확인"}</span></label></section>
  <section class="construction-step-card"><div class="step-no">2</div><div><h4>선행공정 확인</h4><p>${esc(r.prerequisites||"선행공정 완료와 작업구역 인계 상태 확인")}</p></div><label class="big-check"><input class="prerequisite-confirm" type="checkbox" ${r.prerequisitesConfirmed?"checked":""}><span>${r.prerequisitesConfirmed?"확인완료":"확인"}</span></label></section>
  <section class="construction-step-card"><div class="step-no">3</div><div><h4>검측</h4><p>공사관리 주담당 · 품질자료와 안전시설은 협조정보로 연결</p></div><select class="inspection-status"><option ${inspection.status==="미요청"?"selected":""}>미요청</option><option ${inspection.status==="검측요청"?"selected":""}>검측요청</option><option ${inspection.status==="검측중"?"selected":""}>검측중</option><option ${inspection.status==="검측완료"?"selected":""}>검측완료</option><option ${inspection.status==="보완"?"selected":""}>보완</option></select></section>
  <section class="construction-step-card"><div class="step-no">4</div><div><h4>시공 진행</h4><p>${done}/${items.length}개 공사 확인항목 완료</p></div><button type="button" class="secondary-btn toggle-construction-items">체크항목 보기</button></section>
  <section class="construction-step-card"><div class="step-no">5</div><div><h4>양생·후속공정</h4><p>${esc(r.curingPlan||"양생기간과 후속공정 착수조건을 확인하세요.")}</p></div><label class="big-check"><input class="curing-confirm" type="checkbox" ${r.curingConfirmed?"checked":""}><span>${r.curingConfirmed?"확인완료":"확인"}</span></label></section>
  <section class="construction-step-card"><div class="step-no">6</div><div><h4>인수인계</h4><p>${work.handovers.length?`${work.handovers.length}건 기록됨`:"후속 작업자에게 작업구역 상태를 인계합니다."}</p></div><button type="button" class="secondary-btn add-handover">인계 추가</button></section>
 </div>
 <div class="construction-items-panel" hidden><h4>공정별 확인항목</h4><div class="construction-check-list">${items.length?items.map(x=>`<label><input class="construction-task-check" type="checkbox" data-task-id="${x.task.taskId}" data-index="${x.index}" ${x.checked?"checked":""}><span>${esc(x.item)}</span></label>`).join(""):"<p class='help-text'>자동 생성된 공사 확인항목이 없습니다.</p>"}</div></div>
 <details class="simple-detail-section construction-details"><summary>자세히 입력</summary>
  <div class="construction-grid"><section><h4>작업계획·시공순서</h4><label>작업계획서 핵심내용<textarea class="construction-work-plan">${esc(r.workPlan||"")}</textarea></label><label>시공순서<textarea class="construction-sequence">${esc(r.sequence||"")}</textarea></label></section><section><h4>양생·간섭관리</h4><label>양생 및 후속공정 계획<textarea class="construction-curing-plan">${esc(r.curingPlan||"")}</textarea></label><label>동시작업·장비동선<textarea class="construction-interference">${esc(r.interference||"")}</textarea></label></section></div>
  <div class="construction-grid"><section><h4>검측 상세</h4><input class="inspection-inspector" placeholder="검측자·감리" value="${esc(inspection.inspector||"")}"><input class="inspection-result" placeholder="검측결과·보완사항" value="${esc(inspection.result||"")}"></section><section><h4>담당·특이사항</h4><input class="construction-manager" placeholder="담당자" value="${esc(r.manager||"")}"><textarea class="construction-notes" placeholder="특이사항">${esc(r.notes||"")}</textarea></section></div>
  <div class="construction-grid"><section><h4>도면 확인</h4><div class="construction-record-list">${work.drawings.map(d=>`<label><input class="drawing-check" type="checkbox" data-drawing-id="${d.drawingId}" ${d.status==="확인완료"?"checked":""}><span>${esc(d.title)} ${d.revision?`· ${esc(d.revision)}`:""}</span><b>${esc(d.status)}</b></label>`).join("")||"<p class='help-text'>등록된 도면이 없습니다.</p>"}</div><button class="secondary-btn add-drawing">도면 추가</button></section><section><h4>인수인계 기록</h4><div class="construction-record-list">${work.handovers.map(h=>`<div><span>${esc(h.from||"인계자 미입력")} → ${esc(h.to||"인수자 미입력")}</span><p>${esc(h.content)}</p></div>`).join("")||"<p class='help-text'>등록된 인수인계가 없습니다.</p>"}</div></section></div>
 </details>
 <button class="primary-btn save-construction">저장</button></article>`;
}
export function renderConstruction(root){
 ensureConstructionState();const date=todayYmd(),works=constructionWorkForDate(date);const inspections=works.filter(w=>w.inspection?.status==="검측완료").length,completed=works.filter(w=>w.record?.status==="완료").length,plans=works.filter(w=>w.record?.workPlanConfirmed).length;
 root.innerHTML=`<div class="section-head"><div><h2>CONSTRUCTION · 공사관리</h2><p>작업계획, 선행공정, 검측, 시공, 양생, 인수인계를 확인 중심으로 관리합니다.</p></div><button class="secondary-btn" onclick="window.print()">출력</button></div>
 <div class="summary-grid construction-summary"><article class="summary-card risk-blue"><div class="label">오늘 작업</div><strong>${works.length}건</strong><p>일정에서 자동 연결</p></article><article class="summary-card risk-blue"><div class="label">계획 확인</div><strong>${plans}/${works.length}</strong><p>작업계획서 기준</p></article><article class="summary-card risk-orange"><div class="label">검측 완료</div><strong>${inspections}/${works.length}</strong><p>공사관리 주담당</p></article><article class="summary-card risk-green"><div class="label">완료 작업</div><strong>${completed}건</strong><p>진행상태 기준</p></article></div>
 <div class="construction-role-note"><b>공사관리 주담당</b><span>작업계획서 · 검측 · 시공순서 · 선행공정 · 양생 · 인수인계</span><small>품질시험과 안전시설은 각 담당부서의 협조정보를 한 번만 참조합니다.</small></div>
 <div class="construction-work-list">${works.length?works.map(card).join(""):"<div class='empty-state'><h3>오늘 연결된 공사작업이 없습니다.</h3><p>일정 또는 오늘업무에서 작업을 등록하면 자동 생성됩니다.</p></div>"}</div>`;
 root.querySelectorAll(".construction-quick-status").forEach(btn=>btn.addEventListener("click",()=>{const c=btn.closest(".construction-work-card");saveConstructionRecord(c.dataset.workId,{status:btn.dataset.status});renderConstruction(root);}));
 root.querySelectorAll(".toggle-construction-items").forEach(btn=>btn.addEventListener("click",()=>{const p=btn.closest(".construction-work-card").querySelector(".construction-items-panel");p.hidden=!p.hidden;btn.textContent=p.hidden?"체크항목 보기":"체크항목 닫기";}));
 root.querySelectorAll(".construction-task-check").forEach(el=>el.addEventListener("change",()=>{toggleConstructionTaskItem(el.dataset.taskId,Number(el.dataset.index),el.checked);}));
 root.querySelectorAll(".save-construction").forEach(btn=>btn.addEventListener("click",()=>{const c=btn.closest(".construction-work-card"),status=c.querySelector(".construction-quick-status.active")?.dataset.status||"확인";saveConstructionRecord(c.dataset.workId,{status,workPlanConfirmed:c.querySelector(".work-plan-confirm").checked,prerequisitesConfirmed:c.querySelector(".prerequisite-confirm").checked,curingConfirmed:c.querySelector(".curing-confirm").checked,workPlan:c.querySelector(".construction-work-plan").value,sequence:c.querySelector(".construction-sequence").value,curingPlan:c.querySelector(".construction-curing-plan").value,interference:c.querySelector(".construction-interference").value,manager:c.querySelector(".construction-manager").value,notes:c.querySelector(".construction-notes").value});const s=c.querySelector(".inspection-status").value;saveConstructionInspection(c.dataset.workId,{status:s,inspector:c.querySelector(".inspection-inspector").value,result:c.querySelector(".inspection-result").value,requestedAt:s==="검측요청"?new Date().toISOString():"",inspectedAt:["검측완료","보완"].includes(s)?new Date().toISOString():""});renderConstruction(root);}));
 root.querySelectorAll(".add-drawing").forEach(btn=>btn.addEventListener("click",()=>{const c=btn.closest(".construction-work-card"),title=prompt("도면명 또는 도면번호를 입력하세요.");if(title){addConstructionDrawing(c.dataset.workId,{title,revision:prompt("Revision을 입력하세요.","")||""});renderConstruction(root);}}));
 root.querySelectorAll(".drawing-check").forEach(el=>el.addEventListener("change",()=>{toggleConstructionDrawing(el.dataset.drawingId,el.checked);renderConstruction(root);}));
 root.querySelectorAll(".add-handover").forEach(btn=>btn.addEventListener("click",()=>{const c=btn.closest(".construction-work-card"),content=prompt("인수인계 내용을 입력하세요.","작업구역 상태와 후속공정 착수조건 확인")||"";if(content){addConstructionHandover(c.dataset.workId,{from:prompt("인계자","")||"",to:prompt("인수자","")||"",content});renderConstruction(root);}}));
}
