import { state, saveLocal } from "../core/state.js";
import { buildExecutiveDashboard } from "../services/executiveDashboard.js";
import { ensureDirectorInstructionState, addDirectorInstruction, updateDirectorInstruction, deleteDirectorInstruction, allOpenInstructions, instructionTiming, instructionTrackingSummary } from "../services/directorInstructions.js";

const esc=v=>String(v??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function go(page,workId="",date=""){if(workId){state.workHubSelectedId=workId;state.workHubDate=date;state.focusWorkId=workId;saveLocal();}document.querySelector(`.main-tabs .tab[data-page="${page}"]`)?.click();}
const roleOptions=["안전관리","품질관리","공사관리","자재·장비","현장소장"];

function instructionBoard(d){
  ensureDirectorInstructionState();
  const date=d.briefing.date, rows=(state.directorInstructions||[]).filter(x=>x.workDate===date).sort((a,b)=>String(a.status==="완료")-String(b.status==="완료")||String(a.dueTime||"99:99").localeCompare(String(b.dueTime||"99:99")));
  const open=allOpenInstructions(date), tracking=instructionTrackingSummary(date);
  return `<section class="card director-command-board"><div class="section-head"><div><h3>현장소장 지시·조치 관리</h3><p>지시는 Work ID에 연결되며 담당영역 화면과 WORK HUB에서 동일하게 확인됩니다.</p></div><div class="command-track-kpis"><div class="command-count"><b>${open.length}</b><span>미완료</span></div><div class="command-count danger"><b>${tracking.overdue}</b><span>기한초과</span></div><div class="command-count warn"><b>${tracking.notStarted}</b><span>미착수</span></div><div class="command-count hold"><b>${tracking.longHold}</b><span>장기보류</span></div></div></div>
  <form id="directorInstructionForm" class="director-command-form simple-command-form">
    <label>어느 작업인가요?<select name="workId" required>${d.briefing.ranked.map(x=>`<option value="${esc(x.work.workId)}">${esc(x.work.subProcess||x.work.title)} · ${esc(x.work.location||x.work.workId)}</option>`).join("")}</select></label>
    <label>누가 할 일인가요?<select name="role">${roleOptions.map(x=>`<option>${x}</option>`).join("")}</select></label>
    <label class="command-text">무엇을 해야 하나요?<textarea name="text" required placeholder="예: 타설 전 검측을 완료하고 결과를 보고하세요."></textarea></label>
    <label>언제까지?<select name="duePreset"><option value="today" selected>오늘</option><option value="tomorrow">내일</option><option value="custom">날짜 직접 선택</option></select></label>
    <button class="primary-btn command-submit" type="submit" ${d.total?"":"disabled"}>지시 등록</button>
    <details class="command-advanced"><summary>담당자·시간 등 자세히 입력</summary><div class="command-advanced-grid">
      <label>담당자<input name="assignee" placeholder="비워도 됩니다"></label>
      <label>날짜<input name="dueDate" type="date" value="${esc(date)}"></label>
      <label>시간<input name="dueTime" type="time"></label>
      <label>우선도<select name="priority"><option>긴급</option><option selected>중요</option><option>일반</option></select></label>
    </div></details>
  </form>
  <div class="director-command-list">${rows.map(x=>{const timing=instructionTiming(x);return `<article class="command-item priority-${esc(x.priority)} status-${esc(x.status)} timing-${esc(timing.level)}" data-command="${esc(x.instructionId)}"><div class="command-main"><div><span>${esc(x.priority)} · ${esc(x.role)} <em class="command-timing ${esc(timing.level)}">${esc(timing.label)}</em></span><strong>${esc(x.text)}</strong><small>${esc([x.workId,x.assignee||"담당자 미지정",`${x.dueDate||""} ${x.dueTime||""}`.trim()].filter(Boolean).join(" · "))}</small></div><button type="button" class="secondary-btn small" data-command-work="${esc(x.workId)}">작업 상세</button></div><div class="command-actions"><select data-command-status><option ${x.status==="지시"?"selected":""}>지시</option><option ${x.status==="진행"?"selected":""}>진행</option><option ${x.status==="완료"?"selected":""}>완료</option><option ${x.status==="보류"?"selected":""}>보류</option></select><input data-command-note value="${esc(x.resultNote||x.handoverNote||"")}" placeholder="조치결과 또는 인계사항"><button type="button" class="secondary-btn small" data-command-save>저장</button><button type="button" class="mini-danger-btn" data-command-delete>삭제</button></div></article>`}).join("")||'<p class="role-clear-message">오늘 등록된 현장소장 지시가 없습니다.</p>'}</div></section>`;
}

export function renderDirectorDashboard(root){
  const d=buildExecutiveDashboard(), top=d.briefing.top;
  root.innerHTML=`<section class="director-hero grade-${d.grade}"><div><span class="eyebrow">EXECUTIVE COMMAND CENTER</span><h2>현장소장 종합 대시보드</h2><p>${esc(d.os.siteName)} · ${esc(d.briefing.date)} · 오늘 현장을 30초 안에 판단합니다.</p></div><div class="director-score"><strong>${d.score}</strong><span>현장 종합점수</span><b>${d.grade}</b></div></section>
  <section class="director-kpi-grid"><article><span>오늘 작업</span><strong>${d.total}</strong><small>Work Instance</small></article><article class="danger"><span>긴급</span><strong>${d.urgent}</strong><small>즉시 지시 필요</small></article><article class="warn"><span>주의</span><strong>${d.caution}</strong><small>작업 전 보완</small></article><article class="ok"><span>정상</span><strong>${d.normal}</strong><small>준비상태 양호</small></article><article><span>평균 준비도</span><strong>${d.briefing.averageReadiness}</strong><small>100점 기준</small></article></section>
  ${top?`<section class="card director-top-priority"><div><span>오늘 1순위 조치</span><h3>${esc(top.work.subProcess||top.work.title)}</h3><p>${esc([top.work.workId,top.work.startTime,top.work.location].filter(Boolean).join(" · "))}</p><ul>${(top.evaluation.reasons||[]).slice(0,4).map(x=>`<li>${esc(x)}</li>`).join("")||"<li>필수 준비사항 충족</li>"}</ul></div><button class="primary-btn" data-open-work="${esc(top.work.workId)}" data-work-date="${esc(top.work.workDate)}">WORK HUB 상세확인</button></section>`:`<section class="card risk-blue"><h3>오늘 등록된 작업이 없습니다.</h3><p>일정 또는 오늘업무에서 작업을 등록하면 종합판정이 자동 생성됩니다.</p></section>`}
  ${instructionBoard(d)}
  <section class="director-main-grid"><article class="card"><div class="mini-head"><div><h3>지연 예상 작업</h3><p class="help-text">착수 전 선결조건이 남아 있는 작업입니다.</p></div><b>${d.delayRisks.length}</b></div><div class="director-list">${d.delayRisks.map(({work,evaluation},i)=>`<button data-open-work="${esc(work.workId)}" data-work-date="${esc(work.workDate)}"><span>${i+1}</span><div><b>${esc(work.subProcess||work.title)}</b><small>${esc([work.startTime,work.location,work.workId].filter(Boolean).join(" · "))}</small><p>${esc((evaluation.reasons||[]).slice(0,3).join(" · "))}</p></div></button>`).join("")||'<p class="role-clear-message">현재 지연 예상 작업이 없습니다.</p>'}</div></article><article class="card"><div class="mini-head"><div><h3>날씨 영향</h3><p class="help-text">오늘 작업순서와 중지 판단에 반영합니다.</p></div><button class="secondary-btn small" data-open-page="weatherPage">날씨 상세</button></div><div class="director-weather">${d.weatherRisks.map(x=>`<div class="${x.level}"><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div>`).join("")}</div><div class="director-weather-metrics"><span>강수 <b>${d.os.weather.maxRain.toFixed(1)}mm</b></span><span>풍속 <b>${d.os.weather.maxWind.toFixed(1)}m/s</b></span><span>체감 <b>${d.os.weather.maxApparent.toFixed(1)}℃</b></span></div></article></section>
  <section class="card"><div class="section-head"><div><h3>AI 현장소장 권장사항</h3><p>현재 통합 DB와 날씨·우선순위 결과를 근거로 생성합니다.</p></div></div><div class="director-ai-grid">${d.aiRecommendations.map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><p>${esc(x)}</p></article>`).join("")||'<p class="help-text">현재 추가 권장사항이 없습니다.</p>'}</div></section>
  <section class="card"><div class="section-head"><div><h3>오늘 작업 전체목록</h3><p>우선순위 순으로 정렬됩니다. 작업을 선택하면 WORK HUB로 이동합니다.</p></div><button class="secondary-btn" data-open-page="workHubPage">전체 WORK HUB</button></div><div class="director-work-table"><div class="director-work-row head"><span>순위</span><span>작업</span><span>시간·위치</span><span>준비도</span><span>판정</span></div>${d.briefing.ranked.map((x,i)=>`<button class="director-work-row" data-open-work="${esc(x.work.workId)}" data-work-date="${esc(x.work.workDate)}"><span>${i+1}</span><span><b>${esc(x.work.subProcess||x.work.title)}</b><small>${esc(x.work.workId)}</small></span><span>${esc([x.work.startTime,x.work.location].filter(Boolean).join(" · ")||"미입력")}</span><span><b>${x.evaluation.readiness}</b></span><span class="level-${x.evaluation.level}">${x.evaluation.level}</span></button>`).join("")}</div></section>`;

  root.querySelectorAll("[data-open-page]").forEach(btn=>btn.addEventListener("click",()=>go(btn.dataset.openPage)));
  root.querySelectorAll("[data-open-work],[data-command-work]").forEach(btn=>btn.addEventListener("click",()=>{const id=btn.dataset.openWork||btn.dataset.commandWork;const w=(state.workInstances||[]).find(x=>x.workId===id);go("workHubPage",id,w?.workDate||d.briefing.date);}));
  root.querySelector("#directorInstructionForm")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),w=(state.workInstances||[]).find(x=>x.workId===f.get("workId"));let dueDate=String(f.get("dueDate")||d.briefing.date);const preset=f.get("duePreset");if(preset==="today") dueDate=d.briefing.date;if(preset==="tomorrow"){const dt=new Date(`${d.briefing.date}T00:00:00+09:00`);dt.setDate(dt.getDate()+1);dueDate=dt.toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"});}addDirectorInstruction({workId:f.get("workId"),workDate:w?.workDate||d.briefing.date,role:f.get("role"),assignee:f.get("assignee"),dueDate,dueTime:f.get("dueTime"),priority:f.get("priority")||"중요",text:f.get("text")});renderDirectorDashboard(root);});
  root.querySelectorAll("[data-command-save]").forEach(btn=>btn.addEventListener("click",()=>{const row=btn.closest("[data-command]");updateDirectorInstruction(row.dataset.command,{status:row.querySelector("[data-command-status]").value,resultNote:row.querySelector("[data-command-note]").value});renderDirectorDashboard(root);}));
  root.querySelectorAll("[data-command-delete]").forEach(btn=>btn.addEventListener("click",()=>{const row=btn.closest("[data-command]");if(confirm("이 지시 이력을 삭제할까요?")){deleteDirectorInstruction(row.dataset.command);renderDirectorDashboard(root);}}));
}
