import { searchKnowledge } from "../services/knowledgeGraph.js";
function nodeCard(n){return `<article class="knowledge-card" data-id="${n.id}"><div class="label">${n.tags.join(" · ")}</div><h3>${n.title}</h3><p>${n.summary}</p><b>5초 요약: ${n.five.slice(0,3).join(" / ")}</b></article>`;}
function detail(n){return `<section class="card"><div class="section-head"><div><h2>${n.title}</h2><p>${n.summary}</p></div><button class="secondary-btn" id="copyKnowledgeBtn">복사</button></div><section class="summary-grid">${n.five.map(x=>`<article class="summary-card risk-orange"><div class="label">5초 요약</div><p>${x}</p></article>`).join("")}</section><details open><summary>품질</summary><div class="action-list">${n.quality.map(x=>`<label class="action-item"><input type="checkbox"><span>${x}</span></label>`).join("")}</div></details><details><summary>안전</summary><div class="action-list">${n.safety.map(x=>`<label class="action-item"><input type="checkbox"><span>${x}</span></label>`).join("")}</div></details><details><summary>사진 기록</summary><div class="action-list">${n.photo.map(x=>`<label class="action-item"><input type="checkbox"><span>${x}</span></label>`).join("")}</div></details><details><summary>관련 기준</summary><div class="action-list">${n.refs.map(x=>`<label class="action-item"><input type="checkbox"><span>${x}</span></label>`).join("")}</div></details></section>`;}
export function renderKnowledge(root){
 const nodes=searchKnowledge("");
 root.innerHTML=`<div class="section-head"><div><h2>KNOWLEDGE · 지식 엔진</h2><p>업무가이드·품질·안전·공종DB를 하나로 통합했습니다.</p></div></div><section class="card"><h3>검색</h3><input id="knowledgeSearch" placeholder="예: 콘크리트, 공시체, 철근, 크레인, 갱폼"></section><section class="knowledge-grid">${nodes.map(nodeCard).join("")}</section><div id="knowledgeDetail">${detail(nodes[0])}</div>`;
 const bind=()=>{root.querySelectorAll(".knowledge-card").forEach(el=>{el.addEventListener("click",()=>{const n=searchKnowledge("").find(x=>x.id===el.dataset.id);root.querySelector("#knowledgeDetail").innerHTML=detail(n);root.querySelector("#copyKnowledgeBtn")?.addEventListener("click",()=>navigator.clipboard.writeText(root.querySelector("#knowledgeDetail").innerText));});});};
 root.querySelector("#knowledgeSearch").addEventListener("input",e=>{const found=searchKnowledge(e.target.value);root.querySelector(".knowledge-grid").innerHTML=found.map(nodeCard).join("")||`<section class="card"><p>검색 결과가 없습니다.</p></section>`;if(found[0])root.querySelector("#knowledgeDetail").innerHTML=detail(found[0]);bind();});
 bind();
}
