import { resourceWorkForDate, ensureResourceState, updateWorkResource, addWorkResource, removeWorkResource, MATERIAL_STATUS, EQUIPMENT_STATUS } from "../services/resourceManagement.js";
import { todayYmd } from "../services/workInstanceDatabase.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const opt=(list,value)=>list.map(x=>`<option ${x===value?"selected":""}>${x}</option>`).join("");
function check(cls,label,on){return `<label class="resource-big-check"><input class="${cls}" type="checkbox" ${on?"checked":""}><span>${label}</span></label>`;}
function materialCard(r){return `<article class="resource-item-card material-card" data-resource-id="${esc(r.resourceId)}"><header><div><span>자재</span><h4>${esc(r.name)}</h4><small>${esc(r.source==="process"?"공정 DB 자동":"직접 추가")}</small></div><button class="icon-btn remove-resource" title="삭제">×</button></header><div class="resource-simple-fields"><label>수량<input class="res-quantity" value="${esc(r.quantity)}" placeholder="예: 120"></label><label>단위<input class="res-unit" value="${esc(r.unit)}" placeholder="㎥, ton, EA"></label><label>업체<input class="res-supplier" value="${esc(r.supplier)}" placeholder="납품업체"></label><label>반입일<input class="res-date" type="date" value="${esc(r.deliveryDate)}"></label><label>상태<select class="res-status">${opt(MATERIAL_STATUS,r.status)}</select></label><label>보관 위치<input class="res-location" value="${esc(r.location)}" placeholder="야적장·층·구역"></label></div><div class="resource-action-grid">${check("res-order","발주 확인",r.orderConfirmed)}${check("res-receipt","반입 확인",r.receiptConfirmed)}${check("res-inspection","수량·외관 검수",r.inspection)}${check("res-quality-doc","품질서류 확인",r.qualityDocumentConfirmed)}${check("res-stock","재고·잔량 확인",r.stockChecked)}</div><details><summary>특이사항</summary><textarea class="res-notes" placeholder="파손, 부족, 반품 등">${esc(r.notes)}</textarea></details><button class="primary-btn save-resource">저장</button></article>`;}
function equipmentCard(r){return `<article class="resource-item-card equipment-card" data-resource-id="${esc(r.resourceId)}"><header><div><span>장비</span><h4>${esc(r.name)}</h4><small>${esc(r.source==="process"?"공정 DB 자동":"직접 추가")}</small></div><button class="icon-btn remove-resource" title="삭제">×</button></header><div class="resource-simple-fields"><label>수량<input class="res-quantity" value="${esc(r.quantity)}" placeholder="예: 1"></label><label>단위<input class="res-unit" value="${esc(r.unit||"대")}"></label><label>업체·기사<input class="res-supplier" value="${esc(r.supplier)}" placeholder="업체 또는 기사"></label><label>반입일<input class="res-date" type="date" value="${esc(r.deliveryDate)}"></label><label>상태<select class="res-status">${opt(EQUIPMENT_STATUS,r.status)}</select></label><label>배치 위치<input class="res-location" value="${esc(r.location)}" placeholder="작업구역"></label></div><div class="resource-action-grid">${check("res-certificate","검사증·보험",r.certificateConfirmed)}${check("res-operator","운전자 자격",r.operatorQualified)}${check("res-daily-check","일상점검",r.dailyCheckConfirmed)}${check("res-placement","배치 확인",r.placementConfirmed)}${check("res-return","반출 확인",r.returnConfirmed)}</div><div class="resource-boundary-note">안전관리자는 작업반경·신호수·아웃트리거·지반상태를 별도로 확인합니다.</div><details><summary>특이사항</summary><textarea class="res-notes" placeholder="고장, 정비, 교체, 반출 등">${esc(r.notes)}</textarea></details><button class="primary-btn save-resource">저장</button></article>`;}
function workSection(work,type){const rows=work.resources.filter(x=>x.type===type);return `<section class="resource-work-section" data-work-id="${esc(work.workId)}"><header><div><span class="work-id-chip">${esc(work.workId)}</span><h3>${esc(work.subProcess||work.title)}</h3><p>${esc(work.location||"위치 미입력")} · ${esc(work.contractor||"협력업체 미입력")}</p></div><b>${rows.length}건</b></header><div class="resource-card-grid">${rows.length?rows.map(type==="자재"?materialCard:equipmentCard).join(""):`<div class="empty-state"><p>연결된 ${type}가 없습니다.</p></div>`}</div><button class="secondary-btn add-resource" data-type="${type}">${type} 추가</button></section>`;}
function readiness(r){if(r.type==="자재")return [r.orderConfirmed,r.receiptConfirmed,r.inspection].filter(Boolean).length;return [r.certificateConfirmed,r.operatorQualified,r.dailyCheckConfirmed,r.placementConfirmed].filter(Boolean).length;}
export function renderResource(root){ensureResourceState();const date=todayYmd(),works=resourceWorkForDate(date),all=works.flatMap(x=>x.resources),materials=all.filter(x=>x.type==="자재"),equipment=all.filter(x=>x.type==="장비"),mReady=materials.filter(x=>rReady(x)).length,eReady=equipment.filter(x=>rReady(x)).length;root.innerHTML=`<div class="section-head"><div><h2>RESOURCE · 자재·장비관리</h2><p>자재는 발주·반입·검수·재고, 장비는 서류·자격·일상점검·배치·반출을 관리합니다.</p></div><button class="secondary-btn" onclick="window.print()">출력</button></div><section class="resource-role-note"><b>업무 구분</b><span>자재·장비 담당은 자원 자체를 관리합니다.</span><small>장비 작업반경·신호수·아웃트리거·지반상태는 안전관리의 작업안전 확인사항입니다.</small></section><div class="resource-kpi-grid"><article><span>자재</span><strong>${mReady}/${materials.length}</strong><small>반입·검수 준비</small></article><article><span>장비</span><strong>${eReady}/${equipment.length}</strong><small>서류·점검·배치</small></article><article><span>오늘 작업</span><strong>${works.length}</strong><small>Work ID 연결</small></article></div><div class="resource-tabs"><button class="resource-tab active" data-tab="material">자재관리</button><button class="resource-tab" data-tab="equipment">장비관리</button></div><div class="resource-tab-panel" data-panel="material">${works.length?works.map(w=>workSection(w,"자재")).join(""):`<div class="empty-state"><h3>오늘 연결된 작업이 없습니다.</h3><p>일정 또는 오늘업무에 작업을 등록하면 필요한 자재가 자동 생성됩니다.</p></div>`}</div><div class="resource-tab-panel" data-panel="equipment" hidden>${works.length?works.map(w=>workSection(w,"장비")).join(""):`<div class="empty-state"><h3>오늘 연결된 작업이 없습니다.</h3><p>일정 또는 오늘업무에 작업을 등록하면 필요한 장비가 자동 생성됩니다.</p></div>`}</div>`;
 root.querySelectorAll(".resource-tab").forEach(btn=>btn.addEventListener("click",()=>{root.querySelectorAll(".resource-tab").forEach(x=>x.classList.toggle("active",x===btn));root.querySelectorAll(".resource-tab-panel").forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.tab);}));
 root.querySelectorAll(".save-resource").forEach(btn=>btn.addEventListener("click",()=>{const c=btn.closest(".resource-item-card"),isMaterial=c.classList.contains("material-card");updateWorkResource(c.dataset.resourceId,{quantity:c.querySelector(".res-quantity").value,unit:c.querySelector(".res-unit").value,supplier:c.querySelector(".res-supplier").value,deliveryDate:c.querySelector(".res-date").value,status:c.querySelector(".res-status").value,location:c.querySelector(".res-location").value,notes:c.querySelector(".res-notes").value,...(isMaterial?{orderConfirmed:c.querySelector(".res-order").checked,receiptConfirmed:c.querySelector(".res-receipt").checked,inspection:c.querySelector(".res-inspection").checked,qualityDocumentConfirmed:c.querySelector(".res-quality-doc").checked,stockChecked:c.querySelector(".res-stock").checked}:{certificateConfirmed:c.querySelector(".res-certificate").checked,operatorQualified:c.querySelector(".res-operator").checked,dailyCheckConfirmed:c.querySelector(".res-daily-check").checked,placementConfirmed:c.querySelector(".res-placement").checked,returnConfirmed:c.querySelector(".res-return").checked})});btn.textContent="저장됨";setTimeout(()=>btn.textContent="저장",900);}));
 root.querySelectorAll(".remove-resource").forEach(btn=>btn.addEventListener("click",()=>{if(confirm("이 항목을 삭제하시겠습니까?")){removeWorkResource(btn.closest(".resource-item-card").dataset.resourceId);renderResource(root);}}));
 root.querySelectorAll(".add-resource").forEach(btn=>btn.addEventListener("click",()=>{const section=btn.closest(".resource-work-section"),type=btn.dataset.type,name=prompt(`${type}명을 입력하세요.`);if(name){const quantity=prompt("수량을 입력하세요.","")||"",unit=prompt("단위를 입력하세요.",type==="장비"?"대":"")||"";addWorkResource(section.dataset.workId,{type,name,quantity,unit});renderResource(root);}}));
}
function rReady(r){return r.type==="자재"?(r.receiptConfirmed&&r.inspection):(r.certificateConfirmed&&r.operatorQualified&&r.dailyCheckConfirmed&&r.placementConfirmed);}
