import { ROLE_RESPONSIBILITY_DB } from "../data/roleResponsibilityDatabase.js";
import { WORK_DOCUMENT_DB } from "../data/workDocumentDatabase.js";
const esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const items=a=>`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;
function card(r){return `<article class="role-scope-card ${r.color}" data-role="${r.roleId}"><header><div><span>업무범위</span><h3>${r.title}</h3><p>${r.subtitle}</p></div><button class="secondary-btn role-scope-detail">자세히 보기</button></header><p class="role-purpose">${r.purpose}</p><div class="role-scope-columns"><section><h4>주담당 업무</h4>${items(r.primary)}</section><section><h4>협조 업무</h4>${items(r.support)}</section><section><h4>주담당이 아닌 업무</h4>${items(r.notPrimary)}</section></div><details><summary>필요 증빙 보기</summary>${items(r.evidence)}</details></article>`;}
function documentCompare(){return `<section class="card document-compare"><div class="mini-head"><h3>작업계획서와 작업허가서 구분</h3><span>서로 다른 문서입니다</span></div><div class="document-compare-grid">${WORK_DOCUMENT_DB.map(d=>`<article class="${d.documentType==='WORK_PLAN'?'risk-green':'risk-red'}"><span>${esc(d.documentType==='WORK_PLAN'?'공사관리 주담당':'안전관리 주담당')}</span><h4>${esc(d.title)}</h4><strong>${esc(d.question)}</strong><p>${esc(d.purpose)}</p>${items(d.contents)}<small>${esc(d.note)}</small></article>`).join("")}</div></section>`;}
function safetyBoundary(){return `<section class="card role-boundary"><div class="mini-head"><h3>안전관리자 겸업 판단 기준</h3><span>참여와 주담당을 구분합니다</span></div><div class="summary-grid"><article class="summary-card risk-blue"><div class="label">가능한 참여</div><strong>안전과 직접 관련된 확인</strong><p>검측 동행 시 안전시설 확인, 자재 하역 시 작업반경·신호수·통로 확인 등은 안전업무로 기록합니다.</p></article><article class="summary-card risk-yellow"><div class="label">주의</div><strong>일시적 보조업무</strong><p>다른 업무를 잠시 돕더라도 안전순찰·교육·위험성평가 등 고유업무 수행에 지장이 없어야 합니다.</p></article><article class="summary-card risk-red"><div class="label">부적절</div><strong>타 업무의 상시 주담당</strong><p>검측 실무, 자재 수불·입출고, 공정관리 등을 반복적으로 전담해 안전업무가 형식화되는 구조는 피합니다.</p></article></div><p class="help-text">GUI's Arc OS는 법적 책임을 단정하지 않고 현장 운영상 기본 역할을 제안합니다. 실제 선임조건과 업무범위는 현행 법령, 발주처 기준, 회사 규정과 현장 조직을 함께 확인해야 합니다.</p></section>`;}
export function renderRoleScope(root){root.innerHTML=`<div class="section-head"><div><h2>ROLE · 부서별 업무범위</h2><p>같은 작업을 여러 부서가 함께 보더라도 주담당은 한 곳으로 지정합니다. 다른 부서는 협조 또는 참고로 연결하며 같은 업무를 중복 입력하지 않습니다.</p></div><button class="secondary-btn" onclick="window.print()">업무분장 출력</button></div><section class="card role-rule"><h3>GUI's Arc OS 업무분장 원칙</h3><div class="summary-grid"><article class="summary-card risk-blue"><div class="label">주담당</div><strong>실제 기록·완료 책임</strong><p>해당 업무를 작성하고 완료 처리합니다.</p></article><article class="summary-card risk-yellow"><div class="label">협조</div><strong>자료·현장확인 지원</strong><p>주담당에게 필요한 정보와 확인을 제공합니다.</p></article><article class="summary-card"><div class="label">참고</div><strong>상태만 열람</strong><p>중복 체크하지 않고 결과만 확인합니다.</p></article></div></section>${safetyBoundary()}${documentCompare()}<nav class="role-scope-filter"><button class="primary-btn" data-filter="all">전체</button>${ROLE_RESPONSIBILITY_DB.map(r=>`<button class="secondary-btn" data-filter="${r.roleId}">${r.title}</button>`).join("")}</nav><section class="role-scope-list">${ROLE_RESPONSIBILITY_DB.map(card).join("")}</section>`;
root.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;root.querySelectorAll('.role-scope-card').forEach(c=>c.hidden=f!=='all'&&c.dataset.role!==f);root.querySelectorAll('[data-filter]').forEach(x=>x.className=x===b?'primary-btn':'secondary-btn');}));
root.querySelectorAll('.role-scope-detail').forEach(b=>b.addEventListener('click',()=>{const d=b.closest('article').querySelector('details');d.open=!d.open;}));}
