import { ensureTodayData, addTodayActivity, removeTodayActivity, addMaterial, addEquipment, setConcretePlan, buildTodayBriefing, setTodayDocumentCheck, ROLE_LIST } from "../services/todayWorkEngine.js";
import { state, saveLocal } from "../core/state.js";
import { PROCESS_CATEGORIES, PROCESS_INTEGRATION_DB, getProcessesByCategory, getProcessById } from "../data/processIntegrationDatabase.js";
import { buildComplianceAudit, setComplianceAction } from "../services/complianceAudit.js";
import { addWorkEvidence, setWorkApproval } from "../services/evidenceManagement.js";

function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));}
function actionList(items){return items?.length?items.map(x=>`<label class="action-item"><input type="checkbox"><span>${escapeHtml(x)}</span></label>`).join(""):`<p class="help-text">등록된 항목이 없습니다.</p>`;}
function riskLabel(level){return level==="critical"?"최고위험":level==="high"?"고위험":level==="medium"?"주의":"일반";}

function complianceActionButtons(workId,c){
  const status=c.action?.status||"미조치";
  return `<div class="audit-actions"><span class="audit-action-status ${status==='미조치'?'open':'managed'}">${escapeHtml(status)}</span><span class="audit-evidence-count">증빙 ${c.evidence?.length||0}</span><span class="audit-approval-stage">${escapeHtml(c.approval?.stage||"미결재")}</span><button class="mini-btn" data-audit-move="${escapeHtml(c.targetPage)}">${escapeHtml(c.target)} 이동</button><button class="mini-btn" data-evidence-add="1" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">증빙등록</button><button class="mini-btn" data-approval-set="검토완료" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">검토</button><button class="mini-btn" data-approval-set="현장소장 승인" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">소장결재</button><button class="mini-btn" data-audit-action="완료" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">완료보고</button><button class="mini-btn" data-audit-action="보류" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">보류</button><button class="mini-btn" data-audit-action="예외" data-work-id="${escapeHtml(workId)}" data-rule-id="${escapeHtml(c.ruleId)}">예외</button></div>`;
}
function complianceBoard(audit){
  if(!audit.totalWorks) return `<p class="help-text">오늘 작업을 등록하면 Work ID별 누락검사가 시작됩니다.</p>`;
  return `<div class="compliance-summary"><article><span>작업</span><strong>${audit.totalWorks}</strong></article><article class="danger"><span>즉시 확인</span><strong>${audit.criticalCount}</strong></article><article class="warn"><span>보완</span><strong>${audit.warnCount}</strong></article><article><span>대응기록</span><strong>${audit.managedCount||0}</strong></article></div><div class="compliance-work-list">${audit.works.map(w=>`<article class="compliance-work ${w.criticalCount?"has-critical":w.warnCount?"has-warn":"all-ok"}"><header><div><span class="work-id-chip">${escapeHtml(w.workId)}</span><h4>${escapeHtml(w.subProcess||w.title)}</h4><p>${escapeHtml(w.location||"위치 미입력")}</p></div><b>${w.openMissing.length?`미조치 ${w.openMissing.length}건`:w.missing.length?"대응기록 완료":"이상 없음"}</b></header><div>${w.checks.map(c=>`<span class="audit-chip ${c.ok?"ok":c.severity}">${c.ok?"✓":"!"} ${escapeHtml(c.title)}</span>`).join("")}</div>${w.missing.length?`<ul>${w.missing.map(c=>`<li><div class="audit-item-main"><strong>${escapeHtml(c.title)}</strong><span>${escapeHtml(c.detail)}</span>${c.action?.reason?`<small>사유: ${escapeHtml(c.action.reason)}</small>`:""}</div>${complianceActionButtons(w.workId,c)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div>`;
}
function bindComplianceActions(root,rerender){
  root.querySelectorAll("[data-audit-move]").forEach(btn=>btn.addEventListener("click",()=>document.querySelector(`.main-tabs .tab[data-page='${btn.dataset.auditMove}']`)?.click()));
  root.querySelectorAll("[data-evidence-add]").forEach(btn=>btn.addEventListener("click",()=>{const name=prompt("증빙명 또는 파일명을 입력하세요.")||"";if(!name)return;const type=prompt("증빙 유형을 입력하세요. (사진/문서/서명)","사진")||"사진";const author=prompt("작성자 또는 등록자를 입력하세요.")||"";addWorkEvidence({workId:btn.dataset.workId,ruleId:btn.dataset.ruleId,type,name,author});rerender();}));
  root.querySelectorAll("[data-approval-set]").forEach(btn=>btn.addEventListener("click",()=>{const person=prompt(`${btn.dataset.approvalSet} 담당자명을 입력하세요.`)||"";if(!person)return;setWorkApproval(btn.dataset.workId,btn.dataset.ruleId,btn.dataset.approvalSet,person);rerender();}));
  root.querySelectorAll("[data-audit-action]").forEach(btn=>btn.addEventListener("click",()=>{const status=btn.dataset.auditAction;const reason=status==="완료"?"":prompt(`${status} 사유를 입력하세요.`)||"";if(status!=="완료"&&!reason)return;setComplianceAction(btn.dataset.workId,btn.dataset.ruleId,status,reason);rerender();}));
}

function activityCards(today){
  if(!today.activities.length) return `<p class="help-text">오늘 세부 작업을 등록하면 공종별 위험요인과 필수서류가 자동 연결됩니다.</p>`;
  return today.activities.map(a=>{const p=getProcessById(a.processId);if(!p)return"";return `<article class="today-process-card risk-${escapeHtml(p.riskLevel)}">
    <div class="today-process-head"><div><span>${escapeHtml(p.category)} · ${escapeHtml(a.workId || "WORK 연결중")}</span><h4>${escapeHtml(p.subProcess)}</h4><p>${escapeHtml([a.location,a.contractor,a.workers?`${a.workers}명`:"",a.startTime&&a.endTime?`${a.startTime}~${a.endTime}`:"",a.detail].filter(Boolean).join(" · ")||"세부 정보 미입력")}</p></div><div><b>${riskLabel(p.riskLevel)}</b><button class="mini-btn danger" data-remove-activity="${a.id}">삭제</button></div></div>
    <details><summary>자동 연결 내용 보기</summary><div class="process-auto-grid"><div><strong>주요 위험</strong><ul>${p.safetyRisks.slice(0,5).map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div><div><strong>예방조치</strong><ul>${p.preventiveActions.slice(0,5).map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div><div><strong>필요서류</strong><ul>${p.documents.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div></div></details>
  </article>`}).join("");
}

export function renderToday(root){
 const today=ensureTodayData(); const b=buildTodayBriefing(); const audit=buildComplianceAudit(today.date); const firstCategory=PROCESS_CATEGORIES[0]; const simple=state.uiSimpleMode!==false;
 const missingTop=audit.openMissing?.slice(0,3)||[];
 root.innerHTML=`
 <div class="section-head"><div><h2>TODAY · 오늘 업무</h2><p>오늘 세부작업을 한 번 등록하면 안전관리·TBM·안전일지·필요서류가 자동으로 연결됩니다.</p></div><div class="export-row"><button id="copyTodayBtn" class="secondary-btn">오늘 브리핑 복사</button><button class="secondary-btn" onclick="window.print()">출력</button></div></div>
 <section class="today-hero"><div><span>오늘 현장 입력</span><h2>${today.date}</h2><p>세부작업 ${today.activities.length}건 · 자재 ${today.materials.length}건 · 장비 ${today.equipment.length}건</p></div><label>내 역할<select id="todayRoleSelect">${ROLE_LIST.map(r=>`<option ${today.role===r?"selected":""}>${r}</option>`).join("")}</select></label></section>
 <section class="simple-today-focus">
   <article class="simple-focus-card primary"><span>오늘 등록 작업</span><strong>${today.activities.length}건</strong><p>${today.activities.length?"등록한 작업에서 할 일이 자동으로 생성됩니다.":"먼저 오늘 작업을 등록하세요."}</p></article>
   <article class="simple-focus-card ${audit.missingCount?"danger":"ok"}"><span>지금 확인할 일</span><strong>${audit.missingCount||0}건</strong><p>${missingTop.map(x=>x.title).join(" · ")||"현재 중요한 누락이 없습니다."}</p></article>
   <article class="simple-focus-card"><span>오늘 준비서류</span><strong>${b.requiredDocuments.filter(x=>!x.checked).length}건</strong><p>준비되면 아래에서 체크하세요.</p></article>
 </section>
 <section class="card today-process-input"><div class="card-title-row"><div><span class="eyebrow">오늘 작업 등록</span><h3>무슨 작업을 하나요?</h3><p>공종과 작업 위치만 선택해도 나머지 업무가 자동으로 연결됩니다.</p></div></div>
   <div class="today-process-form ${simple?"simple-entry":"detailed"}"><label>공종 분류<select id="processCategory">${PROCESS_CATEGORIES.map(x=>`<option>${escapeHtml(x)}</option>`).join("")}</select></label><label>세부 작업<select id="processSelect">${getProcessesByCategory(firstCategory).map(x=>`<option value="${x.id}">${escapeHtml(x.subProcess)}</option>`).join("")}</select></label><label>작업 위치<input id="processLocation" placeholder="예: 201동 8층"></label>${simple?`<details class="today-more-fields"><summary>업체·인원·시간 자세히 입력</summary><div class="today-more-grid"><label>협력업체<input id="processContractor" placeholder="예: ○○건설"></label><label>작업인원<input id="processWorkers" type="number" min="0" placeholder="명"></label><label>시작시간<input id="processStartTime" type="time"></label><label>종료예정<input id="processEndTime" type="time"></label><label class="process-detail-wide">세부내용<input id="processDetail" placeholder="예: 120㎥ / 52M 펌프카 / A구간"></label></div></details>`:`<label>협력업체<input id="processContractor" placeholder="예: ○○건설"></label><label>작업인원<input id="processWorkers" type="number" min="0" placeholder="명"></label><label>시작시간<input id="processStartTime" type="time"></label><label>종료예정<input id="processEndTime" type="time"></label><label class="process-detail-wide">세부내용<input id="processDetail" placeholder="예: 120㎥ / 52M 펌프카 / A구간"></label>`}<button id="addProcessBtn" class="primary-btn today-add-main">이 작업 등록</button></div>
   <div class="today-process-list">${activityCards(today)}</div>
 </section>
 <details class="simple-detail-section" ${simple?"":"open"}><summary>타설·자재·장비 추가 입력</summary><section class="today-input-grid compact">
  <article class="card"><h3>콘크리트 타설 상세</h3><div class="form-grid one"><label>타설량(㎥)<input id="concreteVolume" type="number" value="${today.concrete?.volumeM3||120}"></label><label>타설부위<input id="concretePart" value="${escapeHtml(today.concrete?.part||"슬래브")}"></label><label>펌프카<input id="concretePump" value="${escapeHtml(today.concrete?.pump||"52M")}"></label></div><button id="saveConcreteBtn" class="primary-btn">타설계획 반영</button></article>
  <article class="card"><h3>자재반입</h3><label>자재명<input id="matName" placeholder="예: 철근 D13"></label><label>수량<input id="matQty" placeholder="예: 20Ton"></label><button id="addMaterialBtn" class="secondary-btn">자재 추가</button></article>
  <article class="card"><h3>장비운영</h3><label>장비명<input id="eqName" placeholder="예: 25톤 크레인"></label><label>작업내용<input id="eqTask" placeholder="예: 철근 양중"></label><button id="addEquipmentBtn" class="secondary-btn">장비 추가</button></article>
 </section></details>
 <section class="card compliance-center"><div class="card-title-row"><div><span class="eyebrow">AUTOMATIC MISSING CHECK</span><h3>누락 자동검사</h3><p>통합 Work ID를 기준으로 안전·품질·공사·장비 기록을 교차 확인합니다.</p></div><b>${audit.missingCount?`누락 ${audit.missingCount}건`:"정상"}</b></div>${complianceBoard(audit)}</section>
 <section class="card"><h3>오늘 핵심 확인</h3><div class="summary-grid">${b.actions.slice(0,6).map(x=>`<article class="summary-card risk-orange"><div class="label">자동 연결</div><p>${escapeHtml(x)}</p></article>`).join("")||`<article class="summary-card"><p>오늘 작업을 입력하세요.</p></article>`}</div></section>
 <section class="card"><div class="card-title-row"><div><h3>필요서류 자동 목록</h3><p>준비된 서류를 체크하면 오늘 빠진 것에서 제외됩니다.</p></div></div><div class="document-link-grid">${b.requiredDocuments.length?[...new Map(b.requiredDocuments.map(x=>[`${x.process}:${x.document}`,x])).values()].map(x=>`<label class="action-item ${x.checked?"checked":""}"><input type="checkbox" data-document-key="${escapeHtml(x.key)}" ${x.checked?"checked":""}><span><b>${escapeHtml(x.document)}</b><small>${escapeHtml(x.process)}</small></span></label>`).join(""):`<p class="help-text">세부작업을 등록하면 필요한 안전·품질 서류가 표시됩니다.</p>`}</div></section>
 <details class="simple-detail-section" ${simple?"":"open"}><summary>역할별 전체 업무 보기</summary><section class="card"><h3>역할별 오늘 할 일</h3><div class="role-grid">${Object.entries(b.roleActions).map(([role,list])=>`<article class="role-box ${role===today.role?"role-selected":""}"><h4>${role}</h4><div class="action-list">${actionList(list)}</div></article>`).join("")}</div></section></details>
 <details class="simple-detail-section" ${simple?"":"open"}><summary>TBM 자동 문구 보기</summary><section class="card"><h3>TBM 자동 문구</h3><pre id="todayBriefText" class="tbm-box">${escapeHtml(b.tbm||"오늘 작업을 입력하면 TBM 문구가 생성됩니다.")}</pre></section></details>`;
 bindComplianceActions(root,()=>renderToday(root));
 root.querySelector("#todayRoleSelect").addEventListener("change",e=>{today.role=e.target.value;saveLocal();renderToday(root);});
 root.querySelector("#processCategory").addEventListener("change",e=>{const select=root.querySelector("#processSelect");select.innerHTML=getProcessesByCategory(e.target.value).map(x=>`<option value="${x.id}">${escapeHtml(x.subProcess)}</option>`).join("");});
 root.querySelector("#addProcessBtn").addEventListener("click",()=>{addTodayActivity({processId:root.querySelector("#processSelect").value,location:root.querySelector("#processLocation").value,contractor:root.querySelector("#processContractor").value,workers:root.querySelector("#processWorkers").value,startTime:root.querySelector("#processStartTime").value,endTime:root.querySelector("#processEndTime").value,detail:root.querySelector("#processDetail").value});renderToday(root);});
 root.querySelectorAll("[data-document-key]").forEach(input=>input.addEventListener("change",()=>{setTodayDocumentCheck(input.dataset.documentKey,input.checked);renderToday(root);}));
 root.querySelectorAll("[data-remove-activity]").forEach(btn=>btn.addEventListener("click",()=>{removeTodayActivity(btn.dataset.removeActivity);renderToday(root);}));
 root.querySelector("#saveConcreteBtn").addEventListener("click",()=>{setConcretePlan({volumeM3:Number(root.querySelector("#concreteVolume").value),part:root.querySelector("#concretePart").value,pump:root.querySelector("#concretePump").value});renderToday(root);});
 root.querySelector("#addMaterialBtn").addEventListener("click",()=>{addMaterial({name:root.querySelector("#matName").value,qty:root.querySelector("#matQty").value});renderToday(root);});
 root.querySelector("#addEquipmentBtn").addEventListener("click",()=>{addEquipment({name:root.querySelector("#eqName").value,task:root.querySelector("#eqTask").value});renderToday(root);});
 root.querySelector("#copyTodayBtn").addEventListener("click",()=>{navigator.clipboard.writeText(root.querySelector("#todayBriefText").innerText);alert("오늘 브리핑을 복사했습니다.");});
}
