PRAGMA foreign_keys = ON;

CREATE TABLE workforce_profiles (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE REFERENCES users(id),status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','SUSPENDED','REJECTED','LEFT_SITE')),phone_encrypted TEXT,birth_date_encrypted TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE workforce_site_enrollments (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),site_id TEXT NOT NULL REFERENCES sites(id),company_id TEXT NOT NULL REFERENCES companies(id),site_contractor_id TEXT REFERENCES company_site_contracts(id),trade_id TEXT,approval_status TEXT NOT NULL DEFAULT 'PENDING' CHECK(approval_status IN ('PENDING','APPROVED','SUSPENDED','REJECTED','LEFT_SITE')),approved_by TEXT REFERENCES users(id),approved_at TEXT,first_approved_work_date TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,revision INTEGER NOT NULL DEFAULT 1,UNIQUE(user_id,site_id));
CREATE TABLE workforce_devices (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),device_identifier_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','REVOKED')),registered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_used_at TEXT,revoked_at TEXT,UNIQUE(user_id,device_identifier_hash));
CREATE TABLE workforce_qr_sessions (id TEXT PRIMARY KEY,site_id TEXT NOT NULL REFERENCES sites(id),qr_token_hash TEXT NOT NULL UNIQUE,issued_at TEXT NOT NULL,expires_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','EXPIRED','REVOKED')),issued_by TEXT NOT NULL REFERENCES users(id),key_version TEXT NOT NULL);
CREATE TABLE workforce_attendance (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),site_id TEXT NOT NULL REFERENCES sites(id),company_id TEXT NOT NULL REFERENCES companies(id),site_contractor_id TEXT REFERENCES company_site_contracts(id),trade_id TEXT,work_date TEXT NOT NULL,check_in_at TEXT NOT NULL,check_out_at TEXT,attendance_status TEXT NOT NULL DEFAULT 'PRESENT' CHECK(attendance_status IN ('PRESENT','CHECKED_OUT','ADJUSTED')),source TEXT NOT NULL DEFAULT 'DYNAMIC_QR',approved_by TEXT REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,revision INTEGER NOT NULL DEFAULT 1,UNIQUE(user_id,site_id,work_date));
CREATE TABLE workforce_attendance_events (id TEXT PRIMARY KEY,attendance_id TEXT REFERENCES workforce_attendance(id),event_type TEXT NOT NULL,actor_user_id TEXT REFERENCES users(id),event_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,metadata_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE workforce_idempotency (key_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),payload_hash TEXT NOT NULL,response_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT NOT NULL);

CREATE INDEX idx_workforce_attendance_status ON workforce_attendance(site_id,work_date,attendance_status);
CREATE INDEX idx_workforce_attendance_company ON workforce_attendance(site_id,company_id,work_date);
CREATE INDEX idx_workforce_attendance_trade ON workforce_attendance(site_id,trade_id,work_date);
CREATE INDEX idx_workforce_qr_expiry ON workforce_qr_sessions(site_id,expires_at);
CREATE INDEX idx_workforce_devices_status ON workforce_devices(user_id,status);
CREATE INDEX idx_workforce_enrollment_scope ON workforce_site_enrollments(site_id,company_id,approval_status);

INSERT OR IGNORE INTO permissions(id,code,module_code) VALUES
 ('perm-module-workforce-access','module.workforce.access','workforce'),('perm-workforce-read','workforce.read','workforce'),('perm-workforce-read-all','workforce.read_all','workforce'),('perm-workforce-enroll','workforce.enroll','workforce'),('perm-workforce-approve','workforce.approve','workforce'),('perm-workforce-reject','workforce.reject','workforce'),('perm-workforce-generate-qr','workforce.generate_qr','workforce'),('perm-workforce-check-in','workforce.check_in','workforce'),('perm-workforce-adjust','workforce.adjust','workforce'),('perm-workforce-view-statistics','workforce.view_statistics','workforce'),('perm-workforce-manage-devices','workforce.manage_devices','workforce');
INSERT OR IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.module_code='workforce' WHERE r.code='SITE_MANAGER';
INSERT OR IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('module.workforce.access','workforce.read','workforce.approve','workforce.reject','workforce.generate_qr','workforce.view_statistics') WHERE r.code='GENERAL_CONTRACTOR_STAFF';
INSERT OR IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('module.workforce.access','workforce.read','workforce.approve','workforce.reject','workforce.view_statistics') WHERE r.code='CONTRACTOR_MANAGER';
INSERT OR IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('module.workforce.access','workforce.enroll','workforce.check_in') WHERE r.code='FIELD_WORKER';
