import {ApiError} from "../../core/response.js";
import {fingerprintLocationMaster} from "./diff.js";

const LIMIT=90,groups=(items,width)=>{const size=Math.max(1,Math.floor(LIMIT/width));return Array.from({length:Math.ceil(items.length/size)},(_,i)=>items.slice(i*size,(i+1)*size))};
const values=(count,width)=>Array.from({length:count},(_,r)=>`(${Array.from({length:width},(_,c)=>`?${r*width+c+1}`).join(",")})`).join(",");
const bindRows=(statement,rows,fields)=>statement.bind(...rows.flatMap(row=>fields.map(field=>row[field]??null))),by=(diff,type)=>diff.operations.filter(item=>item.type===type);
function parentFirst(items){const map=new Map(items.map(item=>[item.id,item])),visiting=new Set(),done=new Set(),out=[];const visit=item=>{if(done.has(item.id))return;if(visiting.has(item.id))throw new ApiError(409,"LOCATION_IMPORT_PREVIEW_STALE","The parent graph changed.");visiting.add(item.id);const parent=map.get(item.after.parentId);if(parent)visit(parent);visiting.delete(item.id);done.add(item.id);out.push(item)};for(const item of items)visit(item);return out}
function resultSnapshot(current,diff){const locations=new Map((current.locations??[]).map(row=>[row.id,{...row}])),aliases=new Map((current.aliases??[]).map(row=>[row.id,{...row}]));for(const item of diff.operations){if(["ADD","UPDATE","INACTIVE"].includes(item.type))locations.set(item.id,{...item.after});if(["ALIAS_ADD","ALIAS_UPDATE","ALIAS_INACTIVE"].includes(item.type))aliases.set(item.id,{...item.after})}return{locations:[...locations.values()],aliases:[...aliases.values()]}}

export function buildLocationImportApplyStatements(env,{importRow,siteId,userId,idempotencyKey,payloadHash,diff,requestId,response}){
  const statements=[env.DB.prepare("UPDATE site_location_imports SET status='APPLYING' WHERE id=?1 AND site_id=?2 AND status='READY' AND base_master_revision=?3").bind(importRow.id,siteId,Number(importRow.base_master_revision)),env.DB.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM site_location_imports i JOIN site_location_master_revisions r ON r.site_id=i.site_id WHERE i.id=?1 AND i.site_id=?2 AND i.status='APPLYING' AND i.base_master_revision=?3 AND r.revision=?3) THEN 1 ELSE json_extract('', '$') END guarded").bind(importRow.id,siteId,Number(importRow.base_master_revision))];
  const adds=parentFirst(by(diff,"ADD")).map(item=>({...item.after,code:item.id,name:item.after.displayName}));
  for(const group of groups(adds,11))statements.push(bindRows(env.DB.prepare(`INSERT INTO site_locations(id,site_id,parent_id,location_type,code,name,display_name,sort_order,canonical_key,source,is_active) VALUES ${values(group.length,11)}`),group,["id","siteId","parentId","locationType","code","name","displayName","sortOrder","canonicalKey","source","isActive"]));
  for(const item of [...by(diff,"UPDATE"),...by(diff,"INACTIVE")])statements.push(env.DB.prepare("UPDATE site_locations SET parent_id=?3,location_type=?4,code=?1,name=?5,display_name=?5,sort_order=?6,is_active=?7,updated_at=CURRENT_TIMESTAMP WHERE id=?1 AND site_id=?2 AND canonical_key=?8 AND source='IMPORT'").bind(item.id,siteId,item.after.parentId,item.after.locationType,item.after.displayName,item.after.sortOrder,item.after.isActive,item.after.canonicalKey));
  for(const group of groups(by(diff,"ALIAS_ADD").map(item=>item.after),8))statements.push(bindRows(env.DB.prepare(`INSERT INTO site_location_aliases(id,site_id,location_id,alias_text,normalized_alias,alias_type,source,is_active) VALUES ${values(group.length,8)}`),group,["id","siteId","locationId","aliasText","normalizedAlias","aliasType","source","isActive"]));
  for(const item of [...by(diff,"ALIAS_UPDATE"),...by(diff,"ALIAS_INACTIVE")])statements.push(env.DB.prepare("UPDATE site_location_aliases SET alias_text=?3,alias_type=?4,is_active=?5,updated_at=CURRENT_TIMESTAMP WHERE id=?1 AND site_id=?2 AND normalized_alias=?6 AND source='IMPORT'").bind(item.id,siteId,item.after.aliasText,item.after.aliasType,item.after.isActive,item.after.normalizedAlias));
  statements.push(env.DB.prepare("UPDATE site_location_imports SET status='APPLIED',applied_at=CURRENT_TIMESTAMP,post_master_fingerprint=?3,added_count=?4,updated_count=?5,unchanged_count=?6,inactivated_count=?7,alias_added_count=?8,alias_updated_count=?9,alias_inactivated_count=?10,error_count=0 WHERE id=?1 AND site_id=?2 AND status='APPLYING'").bind(importRow.id,siteId,response.newMasterFingerprint,diff.counts.added,diff.counts.updated,diff.counts.unchanged,diff.counts.inactivated,diff.counts.aliasAdded,diff.counts.aliasUpdated,diff.counts.aliasInactivated),env.DB.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM site_location_imports WHERE id=?1 AND site_id=?2 AND status='APPLIED' AND post_master_fingerprint=?3) THEN 1 ELSE json_extract('', '$') END guarded").bind(importRow.id,siteId,response.newMasterFingerprint),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,outcome,request_id,metadata_json) VALUES(?1,?2,'SITE_LOCATION_IMPORT_APPLIED','ALLOWED',?3,?4)").bind(crypto.randomUUID(),userId,requestId,JSON.stringify({siteId,importId:importRow.id,counts:diff.counts,newMasterFingerprint:response.newMasterFingerprint})),env.DB.prepare("INSERT INTO site_location_import_idempotency(site_id,import_id,user_id,idempotency_key,payload_hash,response_json,expires_at) VALUES(?1,?2,?3,?4,?5,?6,datetime('now','+7 days'))").bind(siteId,importRow.id,userId,idempotencyKey,payloadHash,JSON.stringify(response)));
  return statements;
}

export async function applyLocationImport({env,repository,importRow,siteId,userId,idempotencyKey,payloadHash,diff,fileHash,requestId,currentSnapshot,postApplySnapshot}){
  const replay=await repository.getApplyReplay(env,{siteId,userId,importId:importRow.id,idempotencyKey});if(replay){if(replay.payload_hash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_PAYLOAD_MISMATCH","The Idempotency-Key was reused with another payload.");return replay.response??JSON.parse(replay.response_json)}
  if((fileHash??importRow.file_hash)!==importRow.file_hash||diff.baseMasterFingerprint!==importRow.base_master_fingerprint||diff.previewHash!==importRow.preview_hash||diff.counts.error||diff.operations.some(item=>item.type==="ERROR"))throw new ApiError(409,"LOCATION_IMPORT_PREVIEW_STALE","The file, master, or preview changed.");
  const snapshot=currentSnapshot?resultSnapshot(currentSnapshot,diff):(postApplySnapshot??resultSnapshot({locations:[],aliases:[]},diff));const response={importId:importRow.id,status:"APPLIED",counts:diff.counts,newMasterFingerprint:fingerprintLocationMaster(siteId,snapshot)};
  try{await env.DB.batch(buildLocationImportApplyStatements(env,{importRow,siteId,userId,idempotencyKey,payloadHash,diff,requestId,response}));return response}catch(error){const concurrent=await repository.getApplyReplay(env,{siteId,userId,importId:importRow.id,idempotencyKey});if(concurrent){if(concurrent.payload_hash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_PAYLOAD_MISMATCH","The Idempotency-Key was reused with another payload.");return concurrent.response}try{await repository.markLocationImportApplyFailed(env,siteId,importRow.id)}catch{}throw error}
}
