import {ApiError} from "../../core/response.js";
import {fingerprintLocationMaster} from "./diff.js";

export const D1_LOCATION_IMPORT_LIMITS=Object.freeze({maxStatements:20,jsonChunkBytes:1536*1024});
const encoder=new TextEncoder(),by=(diff,type)=>diff.operations.filter(item=>item.type===type);

function parentFirst(items){const map=new Map(items.map(item=>[item.id,item])),visiting=new Set(),done=new Set(),out=[];const visit=item=>{if(done.has(item.id))return;if(visiting.has(item.id))throw new ApiError(409,"LOCATION_IMPORT_PREVIEW_STALE","The parent graph changed.");visiting.add(item.id);const parent=map.get(item.after.parentId);if(parent)visit(parent);visiting.delete(item.id);done.add(item.id);out.push(item)};for(const item of items)visit(item);return out}
function jsonChunks(rows){const chunks=[];let current=[],size=2;const flush=()=>{if(current.length){chunks.push(JSON.stringify(current));current=[];size=2}};for(const row of rows){const serialized=JSON.stringify(row),bytes=encoder.encode(serialized).byteLength;if(bytes+2>D1_LOCATION_IMPORT_LIMITS.jsonChunkBytes)throw new ApiError(413,"LOCATION_IMPORT_APPLY_LIMIT","A workbook row is too large to apply safely.");if(current.length&&size+1+bytes>D1_LOCATION_IMPORT_LIMITS.jsonChunkBytes)flush();current.push(row);size+=bytes+(current.length>1?1:0)}flush();return chunks}
function mutationPayloads(diff){
  const groups=[
    ["LOCATION_UPSERT",parentFirst([...by(diff,"ADD"),...by(diff,"UPDATE")]).map(item=>({...item.after,code:item.id,name:item.after.displayName,source:"IMPORT",isActive:1}))],
    ["LOCATION_INACTIVE",by(diff,"INACTIVE").map(item=>({id:item.id,siteId:item.after.siteId,isActive:0}))],
    ["ALIAS_UPSERT",[...by(diff,"ALIAS_ADD"),...by(diff,"ALIAS_UPDATE")].map(item=>({...item.after,source:"IMPORT",isActive:1}))],
    ["ALIAS_INACTIVE",by(diff,"ALIAS_INACTIVE").map(item=>({id:item.id,siteId:item.after.siteId,isActive:0}))]
  ];
  return groups.flatMap(([kind,rows])=>jsonChunks(rows).map(json=>({kind,json})));
}
export function assessLocationImportApplyCapacity(diff){try{const chunks=mutationPayloads(diff),statementCount=6+chunks.length*2;return{allowed:statementCount<=D1_LOCATION_IMPORT_LIMITS.maxStatements,statementCount,mutationChunks:chunks.length,chunks}}catch(error){if(error?.code==="LOCATION_IMPORT_APPLY_LIMIT")return{allowed:false,statementCount:Infinity,mutationChunks:Infinity,chunks:[]};throw error}}

const SQL={
  LOCATION_UPSERT:`INSERT INTO site_locations(id,site_id,parent_id,location_type,code,name,display_name,sort_order,canonical_key,source,is_active)
    SELECT json_extract(j.value,'$.id'),json_extract(j.value,'$.siteId'),json_extract(j.value,'$.parentId'),json_extract(j.value,'$.locationType'),json_extract(j.value,'$.code'),json_extract(j.value,'$.name'),json_extract(j.value,'$.displayName'),CAST(json_extract(j.value,'$.sortOrder') AS INTEGER),json_extract(j.value,'$.canonicalKey'),'IMPORT',1 FROM json_each(?1) j WHERE 1
    ON CONFLICT(id) DO UPDATE SET parent_id=excluded.parent_id,location_type=excluded.location_type,code=excluded.code,name=excluded.name,display_name=excluded.display_name,sort_order=excluded.sort_order,is_active=1,updated_at=CURRENT_TIMESTAMP
    WHERE site_locations.site_id=excluded.site_id AND site_locations.canonical_key=excluded.canonical_key AND site_locations.source='IMPORT'`,
  LOCATION_INACTIVE:`UPDATE site_locations SET is_active=0,updated_at=CURRENT_TIMESTAMP WHERE site_id=?1 AND source='IMPORT' AND id IN (SELECT json_extract(value,'$.id') FROM json_each(?2))`,
  ALIAS_UPSERT:`INSERT INTO site_location_aliases(id,site_id,location_id,alias_text,normalized_alias,alias_type,source,is_active)
    SELECT json_extract(j.value,'$.id'),json_extract(j.value,'$.siteId'),json_extract(j.value,'$.locationId'),json_extract(j.value,'$.aliasText'),json_extract(j.value,'$.normalizedAlias'),json_extract(j.value,'$.aliasType'),'IMPORT',1 FROM json_each(?1) j WHERE 1
    ON CONFLICT(id) DO UPDATE SET alias_text=excluded.alias_text,alias_type=excluded.alias_type,is_active=1,updated_at=CURRENT_TIMESTAMP
    WHERE site_location_aliases.site_id=excluded.site_id AND site_location_aliases.location_id=excluded.location_id AND site_location_aliases.normalized_alias=excluded.normalized_alias AND site_location_aliases.source='IMPORT'`,
  ALIAS_INACTIVE:`UPDATE site_location_aliases SET is_active=0,updated_at=CURRENT_TIMESTAMP WHERE site_id=?1 AND source='IMPORT' AND id IN (SELECT json_extract(value,'$.id') FROM json_each(?2))`
};
const GUARD={
  LOCATION_UPSERT:`INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN NOT EXISTS(SELECT 1 FROM json_each(?2) j LEFT JOIN site_locations l ON l.id=json_extract(j.value,'$.id') AND l.site_id=json_extract(j.value,'$.siteId') WHERE l.id IS NULL OR COALESCE(l.parent_id,'')<>COALESCE(json_extract(j.value,'$.parentId'),'') OR l.location_type<>json_extract(j.value,'$.locationType') OR l.code<>json_extract(j.value,'$.code') OR l.name<>json_extract(j.value,'$.name') OR l.display_name<>json_extract(j.value,'$.displayName') OR l.sort_order<>CAST(json_extract(j.value,'$.sortOrder') AS INTEGER) OR l.canonical_key<>json_extract(j.value,'$.canonicalKey') OR l.source<>'IMPORT' OR l.is_active<>1) THEN 'VALID' ELSE 'WRITE_MISMATCH' END`,
  LOCATION_INACTIVE:`INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN NOT EXISTS(SELECT 1 FROM json_each(?2) j LEFT JOIN site_locations l ON l.id=json_extract(j.value,'$.id') AND l.site_id=json_extract(j.value,'$.siteId') WHERE l.id IS NULL OR l.source<>'IMPORT' OR l.is_active<>0) THEN 'VALID' ELSE 'WRITE_MISMATCH' END`,
  ALIAS_UPSERT:`INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN NOT EXISTS(SELECT 1 FROM json_each(?2) j LEFT JOIN site_location_aliases a ON a.id=json_extract(j.value,'$.id') AND a.site_id=json_extract(j.value,'$.siteId') WHERE a.id IS NULL OR a.location_id<>json_extract(j.value,'$.locationId') OR a.alias_text<>json_extract(j.value,'$.aliasText') OR a.normalized_alias<>json_extract(j.value,'$.normalizedAlias') OR a.alias_type<>json_extract(j.value,'$.aliasType') OR a.source<>'IMPORT' OR a.is_active<>1) THEN 'VALID' ELSE 'WRITE_MISMATCH' END`,
  ALIAS_INACTIVE:`INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN NOT EXISTS(SELECT 1 FROM json_each(?2) j LEFT JOIN site_location_aliases a ON a.id=json_extract(j.value,'$.id') AND a.site_id=json_extract(j.value,'$.siteId') WHERE a.id IS NULL OR a.source<>'IMPORT' OR a.is_active<>0) THEN 'VALID' ELSE 'WRITE_MISMATCH' END`
};

function resultSnapshot(current,diff){const locations=new Map((current.locations??[]).map(row=>[row.id,{...row}])),aliases=new Map((current.aliases??[]).map(row=>[row.id,{...row}]));for(const item of diff.operations){if(["ADD","UPDATE","INACTIVE"].includes(item.type)){const old=locations.get(item.id)??{};locations.set(item.id,{...old,...item.after,source:item.after.source??old.source??"IMPORT",isActive:item.after.isActive??old.isActive??old.is_active??1})}if(["ALIAS_ADD","ALIAS_UPDATE","ALIAS_INACTIVE"].includes(item.type)){const old=aliases.get(item.id)??{};aliases.set(item.id,{...old,...item.after,source:item.after.source??old.source??"IMPORT",isActive:item.after.isActive??old.isActive??old.is_active??1})}}return{locations:[...locations.values()],aliases:[...aliases.values()]}}

export function buildLocationImportApplyStatements(env,{importRow,siteId,userId,idempotencyKey,payloadHash,diff,fileHash,artifactObjectKey,requestId,response,applyClaimToken}){
  const capacity=assessLocationImportApplyCapacity(diff);if(!capacity.allowed)throw new ApiError(413,"LOCATION_IMPORT_APPLY_LIMIT","The workbook exceeds the atomic D1 apply limit.");
  const statements=[env.DB.prepare("UPDATE site_location_imports SET apply_claimed_at=apply_claimed_at WHERE id=?1 AND site_id=?2 AND status='APPLYING' AND apply_claim_token=?3 AND datetime(apply_claimed_at)>datetime('now','-15 minutes')").bind(importRow.id,siteId,applyClaimToken),env.DB.prepare("INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN EXISTS(SELECT 1 FROM site_location_imports i JOIN site_location_master_revisions r ON r.site_id=i.site_id WHERE i.id=?2 AND i.site_id=?3 AND i.status='APPLYING' AND i.apply_claim_token=?5 AND datetime(i.apply_claimed_at)>datetime('now','-15 minutes') AND i.cleanup_claim_token IS NULL AND i.base_master_revision=?4 AND r.revision=?4) THEN 'VALID' ELSE 'STALE' END").bind(`${importRow.id}:${idempotencyKey}:revision`,importRow.id,siteId,Number(importRow.base_master_revision),applyClaimToken)];
  for(const [index,chunk] of capacity.chunks.entries()){const args=chunk.kind.endsWith("INACTIVE")?[siteId,chunk.json]:[chunk.json];statements.push(env.DB.prepare(SQL[chunk.kind]).bind(...args),env.DB.prepare(GUARD[chunk.kind]).bind(`${importRow.id}:${idempotencyKey}:${index}`,chunk.json))}
  statements.push(env.DB.prepare("UPDATE site_location_imports SET status='APPLIED',applied_at=CURRENT_TIMESTAMP,artifact_object_key=?4,post_master_fingerprint=?3,added_count=?5,updated_count=?6,unchanged_count=?7,inactivated_count=?8,alias_added_count=?9,alias_updated_count=?10,alias_inactivated_count=?11,error_count=0,apply_claim_token=NULL,apply_claimed_at=NULL WHERE id=?1 AND site_id=?2 AND status='APPLYING' AND apply_claim_token=?12").bind(importRow.id,siteId,response.newMasterFingerprint,artifactObjectKey??null,diff.counts.added,diff.counts.updated,diff.counts.unchanged,diff.counts.inactivated,diff.counts.aliasAdded,diff.counts.aliasUpdated,diff.counts.aliasInactivated,applyClaimToken),env.DB.prepare("INSERT INTO site_location_import_apply_guards(id,guard_value) SELECT ?1,CASE WHEN EXISTS(SELECT 1 FROM site_location_imports WHERE id=?2 AND site_id=?3 AND status='APPLIED' AND apply_claim_token IS NULL AND post_master_fingerprint=?4) THEN 'VALID' ELSE 'WRITE_MISMATCH' END").bind(`${importRow.id}:${idempotencyKey}:result`,importRow.id,siteId,response.newMasterFingerprint),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,outcome,request_id,metadata_json) VALUES(?1,?2,'SITE_LOCATION_IMPORT_APPLIED','ALLOWED',?3,?4)").bind(crypto.randomUUID(),userId,requestId,JSON.stringify({siteId,importId:importRow.id,fileHash:fileHash??importRow.file_hash,artifactObjectKey:artifactObjectKey??null,counts:diff.counts,newMasterFingerprint:response.newMasterFingerprint})),env.DB.prepare("INSERT INTO site_location_import_idempotency(site_id,import_id,user_id,idempotency_key,payload_hash,response_json,expires_at) VALUES(?1,?2,?3,?4,?5,?6,datetime('now','+7 days'))").bind(siteId,importRow.id,userId,idempotencyKey,payloadHash,JSON.stringify(response)));
  if(statements.length>D1_LOCATION_IMPORT_LIMITS.maxStatements)throw new ApiError(413,"LOCATION_IMPORT_APPLY_LIMIT","The workbook exceeds the atomic D1 statement limit.");return statements;
}

async function preserveArtifact(env,{key,bytes,fileHash,fileName,importId}){if(!key||!bytes)return false;const valid=object=>Number(object?.size)===bytes.byteLength&&object?.customMetadata?.sha256===fileHash;const existing=await env.FILES.head?.(key);if(existing){if(!valid(existing))throw new ApiError(409,"LOCATION_IMPORT_ARTIFACT_CONFLICT","The immutable workbook artifact conflicts with this import.");return false}const stored=await env.FILES.put(key,bytes,{onlyIf:{etagDoesNotMatch:"*"},httpMetadata:{contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},customMetadata:{sha256:fileHash,fileName:String(fileName||""),importId:String(importId)}});if(stored)return true;const concurrent=await env.FILES.head?.(key);if(!valid(concurrent))throw new ApiError(409,"LOCATION_IMPORT_ARTIFACT_CONFLICT","The immutable workbook artifact could not be verified.");return false}

export async function applyLocationImport({env,repository,importRow,siteId,userId,idempotencyKey,payloadHash,diff,fileHash,requestId,currentSnapshot,postApplySnapshot,fileBytes,uploadObjectKey,artifactObjectKey}){
  const replay=await repository.getApplyReplay(env,{siteId,userId,importId:importRow.id,idempotencyKey});if(replay){if(replay.payload_hash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_PAYLOAD_MISMATCH","The Idempotency-Key was reused with another payload.");return replay.response??JSON.parse(replay.response_json)}
  if((fileHash??importRow.file_hash)!==importRow.file_hash||diff.baseMasterFingerprint!==importRow.base_master_fingerprint||diff.previewHash!==importRow.preview_hash||diff.counts.error||diff.operations.some(item=>item.type==="ERROR"))throw new ApiError(409,"LOCATION_IMPORT_PREVIEW_STALE","The file, master, or preview changed.");
  const capacity=assessLocationImportApplyCapacity(diff);if(!capacity.allowed)throw new ApiError(413,"LOCATION_IMPORT_APPLY_LIMIT","The workbook exceeds the atomic D1 apply limit.");
  const snapshot=currentSnapshot?resultSnapshot(currentSnapshot,diff):(postApplySnapshot??resultSnapshot({locations:[],aliases:[]},diff)),response={importId:importRow.id,status:"APPLIED",counts:diff.counts,newMasterFingerprint:fingerprintLocationMaster(siteId,snapshot)};
  let ownsApply=false;const applyClaimToken=crypto.randomUUID();
  try{if(repository.beginLocationImportApply){ownsApply=await repository.beginLocationImportApply(env,siteId,importRow.id,applyClaimToken);if(!ownsApply){const concurrent=await repository.getApplyReplay(env,{siteId,userId,importId:importRow.id,idempotencyKey});if(concurrent){if(concurrent.payload_hash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_PAYLOAD_MISMATCH","The Idempotency-Key was reused with another payload.");return concurrent.response??JSON.parse(concurrent.response_json)}throw new ApiError(409,"LOCATION_IMPORT_STATE_INVALID","The import is no longer available to apply.")}}await preserveArtifact(env,{key:artifactObjectKey,bytes:fileBytes,fileHash:fileHash??importRow.file_hash,fileName:importRow.file_name,importId:importRow.id});await env.DB.batch(buildLocationImportApplyStatements(env,{importRow,siteId,userId,idempotencyKey,payloadHash,diff,fileHash,artifactObjectKey,requestId,response,applyClaimToken}))}catch(error){const concurrent=await repository.getApplyReplay(env,{siteId,userId,importId:importRow.id,idempotencyKey});if(concurrent){if(concurrent.payload_hash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_PAYLOAD_MISMATCH","The Idempotency-Key was reused with another payload.");return concurrent.response??JSON.parse(concurrent.response_json)}if(ownsApply)try{await repository.restoreLocationImportApplyReady?.(env,siteId,importRow.id,applyClaimToken)}catch{}if(String(error?.message||error).includes("LOCATION_IMPORT_PREVIEW_STALE"))throw new ApiError(409,"LOCATION_IMPORT_PREVIEW_STALE","The Location Master changed after preview.");throw error}
  if(uploadObjectKey)try{await env.FILES.delete(uploadObjectKey)}catch{}
  return response;
}
