import {ApiError,json,parseJson,requestId} from "./core/response.js";
import {csrfCookie,deriveCredential,safeEqual,sha256} from "./core/security.js";
import {authenticate,context,contextWithTiming,createSession,expiredCsrfCookie,refreshCsrf,revoke} from "./core/session.js";
import {MODULES,MODULE_IMPLEMENTATION} from "./core/permissions.js";
import {VERSION} from "./version.js";
import {d1ProvisioningRepository,provisionAdministrator} from "./core/provisioning.js";
import {manageInternalTestFixture,provisionIssueE2EFixture} from "./core/issue-e2e-provisioning.js";
import {handleIssueRequest} from "./modules/issues.js";
import {handleTodayRequest} from "./modules/today/today-route.js";
import {handleWorkforceRequest} from "./modules/workforce.js";
import {handleConstructionRequest} from "./modules/construction.js";
import {handleConstructionInspectionRequest} from "./modules/construction-inspections.js";
import {handleSafetyRequest} from "./modules/safety.js";
import {handleQualityRequest} from "./modules/quality.js";
import {handleBoardAccessAdminRequest} from "./modules/board-access-admin.js";
import {handleIntegratedAdminRequest} from "./modules/integrated-admin.js";

const audit=(env,actor,action,outcome,id,meta={})=>env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,outcome,request_id,metadata_json) VALUES(?1,?2,?3,?4,?5,?6)").bind(crypto.randomUUID(),actor||null,action,outcome,id,JSON.stringify(meta)).run();
const moduleStatus=code=>({code,label:code,implementationStatus:MODULE_IMPLEMENTATION[code]});
const timingHeader=values=>Object.entries(values).map(([name,value])=>`${name};dur=${Math.max(0,Number(value)||0).toFixed(2)}`).join(", ");
async function loginRate(request,env,identifier){const key=await sha256(`${request.headers.get("cf-connecting-ip")||"unknown"}:${identifier}`),row=await env.DB.prepare("SELECT * FROM rate_limits WHERE key_hash=?1").bind(key).first(),now=Date.now(),max=Number(env.LOGIN_RATE_LIMIT_MAX||8);if(row?.blocked_until&&Date.parse(row.blocked_until)>now)throw new ApiError(429,"LOGIN_RATE_LIMITED","Too many attempts. Try again later.");if(!row||now-Date.parse(row.window_started_at)>900000)await env.DB.prepare("INSERT INTO rate_limits(key_hash,count,window_started_at,blocked_until) VALUES(?1,1,CURRENT_TIMESTAMP,NULL) ON CONFLICT(key_hash) DO UPDATE SET count=1,window_started_at=CURRENT_TIMESTAMP,blocked_until=NULL").bind(key).run();else{const count=Number(row.count)+1;await env.DB.prepare("UPDATE rate_limits SET count=?2,blocked_until=CASE WHEN ?2>=?3 THEN datetime('now','+15 minutes') ELSE blocked_until END WHERE key_hash=?1").bind(key,count,max).run();if(count>=max)throw new ApiError(429,"LOGIN_RATE_LIMITED","Too many attempts. Try again later.")}return key}

export default{async fetch(request,env){const id=requestId(request),url=new URL(request.url),method=request.method;try{
 if(method==="GET"&&(url.pathname==="/"||url.pathname==="/api/health"))return json({ok:true,service:"GUI's Arc Integrated API",version:env.APP_VERSION||VERSION,environment:env.APP_ENV||"development",architecture:"MODULAR_MONOLITH",resources:{worker:true,d1:Boolean(env.DB),r2:Boolean(env.FILES)}});
 if(method==="POST"&&url.pathname==="/api/internal/integration/admin-provision"){if(env.APP_ENV!=="integration"||env.PROVISIONING_ENABLED!=="true"||!env.PROVISIONING_SECRET)throw new ApiError(404,"NOT_FOUND","The requested API path was not found.");const supplied=request.headers.get("x-provisioning-secret")||"";if(!safeEqual(supplied,env.PROVISIONING_SECRET))throw new ApiError(403,"PROVISIONING_DENIED","Provisioning authorization failed.");const body=await parseJson(request),input={displayName:String(body.displayName||"").trim(),identifier:String(body.identifier||"").trim().toLowerCase(),companyName:String(body.companyName||"").trim(),siteName:String(body.siteName||"").trim(),roleCode:String(body.roleCode||"INTEGRATED_OWNER").trim(),credentialHash:String(body.credentialHash||""),credentialSalt:String(body.credentialSalt||""),credentialIterations:Number(body.credentialIterations),requestId:id};if(!input.displayName||!input.identifier||!input.companyName||!/^[a-f0-9]{64}$/.test(input.credentialHash)||!input.credentialSalt||input.credentialIterations!==100000)throw new ApiError(400,"PROVISIONING_INPUT_INVALID","Provisioning input is invalid.");try{return json(await provisionAdministrator(d1ProvisioningRepository(env.DB),input),201)}catch(error){const conflicts=new Set(["ADMIN_IDENTIFIER_EXISTS","AMBIGUOUS_COMPANY_NAME","AMBIGUOUS_SITE_NAME","PERMISSION_MODULE_MISMATCH"]);throw new ApiError(conflicts.has(error.message)?409:500,error.message,"Administrator provisioning failed.")}}
 if(method==="POST"&&url.pathname==="/api/internal/integration/internal-test-site"){if(env.APP_ENV!=="integration"||env.E2E_PROVISIONING_ENABLED!=="true"||!env.E2E_PROVISIONING_SECRET)throw new ApiError(404,"NOT_FOUND","The requested API path was not found.");if(!safeEqual(request.headers.get("x-provisioning-secret")||"",env.E2E_PROVISIONING_SECRET))throw new ApiError(403,"PROVISIONING_DENIED","Provisioning authorization failed.");try{return json(await manageInternalTestFixture(env.DB,await parseJson(request),id))}catch(error){throw new ApiError(400,error.message,"Internal test site management failed.")}}
 if(method==="POST"&&url.pathname==="/api/internal/integration/issue-e2e-provision"){if(env.APP_ENV!=="integration"||env.E2E_PROVISIONING_ENABLED!=="true"||!env.E2E_PROVISIONING_SECRET)throw new ApiError(404,"NOT_FOUND","The requested API path was not found.");if(!safeEqual(request.headers.get("x-provisioning-secret")||"",env.E2E_PROVISIONING_SECRET))throw new ApiError(403,"PROVISIONING_DENIED","Provisioning authorization failed.");try{return json(await provisionIssueE2EFixture(env.DB,await parseJson(request),id),201)}catch(error){const conflicts=new Set(["E2E_FIXTURE_ALREADY_EXISTS","E2E_FIXTURE_IDENTIFIER_INVALID"]);throw new ApiError(conflicts.has(error.message)?409:400,error.message,"Issue E2E fixture provisioning failed.")}}
 if(method==="POST"&&url.pathname==="/api/internal/integration/issue-e2e-control"){if(env.APP_ENV!=="integration"||env.E2E_PROVISIONING_ENABLED!=="true"||!env.E2E_PROVISIONING_SECRET)throw new ApiError(404,"NOT_FOUND","The requested API path was not found.");if(!safeEqual(request.headers.get("x-provisioning-secret")||"",env.E2E_PROVISIONING_SECRET))throw new ApiError(403,"PROVISIONING_DENIED","Provisioning authorization failed.");const body=await parseJson(request),userId=String(body.userId||"");if(!/^e2e-v021-user-[a-z-]+$/.test(userId))throw new ApiError(400,"E2E_CONTROL_SCOPE_INVALID","Only the Integration E2E namespace is allowed.");if(body.action==="ENTITLEMENT"){const status=body.active===true?"ACTIVE":"INACTIVE";await env.DB.batch([env.DB.prepare("UPDATE module_entitlements SET status=?2 WHERE user_id=?1 AND module_code='issue'").bind(userId,status),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,outcome,request_id,metadata_json) VALUES(?1,NULL,'ISSUE_E2E_ENTITLEMENT_MUTATED','ALLOWED',?2,?3)").bind(crypto.randomUUID(),id,JSON.stringify({userId,status}))]);return json({ok:true,action:"ENTITLEMENT",status})}if(body.action==="EXPIRE_SESSIONS"){await env.DB.batch([env.DB.prepare("UPDATE sessions SET idle_expires_at=datetime('now','-1 second') WHERE user_id=?1 AND revoked_at IS NULL").bind(userId),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,outcome,request_id,metadata_json) VALUES(?1,NULL,'ISSUE_E2E_SESSION_EXPIRED','ALLOWED',?2,?3)").bind(crypto.randomUUID(),id,JSON.stringify({userId}))]);return json({ok:true,action:"EXPIRE_SESSIONS"})}throw new ApiError(400,"E2E_CONTROL_ACTION_INVALID","Unsupported Integration E2E control action.")}
 if(method==="POST"&&url.pathname==="/api/v1/auth/login"){const started=performance.now(),body=await parseJson(request),identifier=String(body.identifier||"").trim().toLowerCase(),secret=String(body.pin||""),rateStarted=performance.now(),rateKey=await loginRate(request,env,identifier),rateLimit=performance.now()-rateStarted,userStarted=performance.now(),user=await env.DB.prepare("SELECT id,login_identifier,display_name,credential_hash,credential_salt,credential_iterations,status,context_version FROM users WHERE login_identifier=?1").bind(identifier).first(),userLookup=performance.now()-userStarted,verifyStarted=performance.now(),verified=Boolean(user&&user.status==="ACTIVE"&&safeEqual(await deriveCredential(secret,user.credential_salt,user.credential_iterations),user.credential_hash)),credentialVerify=performance.now()-verifyStarted;if(!verified){await audit(env,user?.id,"LOGIN","DENIED",id);throw new ApiError(401,"LOGIN_FAILED","Check your login information.")}await env.DB.prepare("DELETE FROM rate_limits WHERE key_hash=?1").bind(rateKey).run();const sessionStarted=performance.now(),session=await createSession(request,env,user.id,user.context_version),sessionInsert=performance.now()-sessionStarted,contextResult=await contextWithTiming(env,{user_id:user.id,login_identifier:user.login_identifier,display_name:user.display_name,context_version:user.context_version,selected_site_id:null}),csrfSet=csrfCookie(`${env.SESSION_COOKIE_NAME||"guis_arc_integrated_session"}_csrf`,session.csrf,Number(env.SESSION_IDLE_SECONDS||43200)),auditStarted=performance.now();await audit(env,user.id,"LOGIN","ALLOWED",id);const auditInsert=performance.now()-auditStarted,total=performance.now()-started,timing={rateLimit,userLookup,credentialVerify,sessionInsert,auditInsert,contextMembership:contextResult.timing.membership,contextAuthorization:contextResult.timing.authorizationBatch,contextVisibleModules:contextResult.timing.visibleModules,total};return json({ok:true,csrfToken:session.csrf,context:contextResult.context},200,{"set-cookie":[session.cookie,csrfSet],"server-timing":timingHeader(timing)})}
 if(method==="POST"&&url.pathname==="/api/v1/auth/logout"){const row=await authenticate(request,env,{csrf:true}),expired=await revoke(request,env);await audit(env,row.user_id,"LOGOUT","ALLOWED",id);return json({ok:true},200,{"set-cookie":[expired,expiredCsrfCookie(env)]})}
 if(method==="GET"&&url.pathname==="/api/v1/session"){const started=performance.now(),authStarted=performance.now(),row=await authenticate(request,env),sessionLookup=performance.now()-authStarted,contextResult=await contextWithTiming(env,row),rotated=await refreshCsrf(env,row),total=performance.now()-started,timing={sessionLookup,membership:contextResult.timing.membership,authorizationBatch:contextResult.timing.authorizationBatch,visibleModules:contextResult.timing.visibleModules,total};return json({ok:true,context:contextResult.context,csrfToken:rotated.value},200,{"set-cookie":rotated.cookie,"server-timing":timingHeader(timing)})}
 if(method==="GET"&&url.pathname==="/api/v1/today")return handleTodayRequest(request,env);
 if(method==="GET"&&url.pathname==="/api/v1/modules"){const row=await authenticate(request,env),ctx=await context(env,row);return json({modules:MODULES.map(moduleStatus).filter(v=>(ctx.menuModules||ctx.modules).includes(v.code))})}
 if(method==="POST"&&url.pathname==="/api/v1/context/site"){const row=await authenticate(request,env,{csrf:true}),body=await parseJson(request),siteId=String(body.siteId||""),allowed=await env.DB.prepare("SELECT 1 AS allowed FROM memberships m JOIN sites s ON s.id=m.site_id WHERE m.user_id=?1 AND m.site_id=?2 AND m.status='ACTIVE' AND m.approval_status='APPROVED' AND s.status='ACTIVE'").bind(row.user_id,siteId).first();if(!allowed)throw new ApiError(403,"SITE_SCOPE_DENIED","The selected site is not allowed.");await env.DB.prepare("UPDATE sessions SET selected_site_id=?2 WHERE id=?1").bind(row.id,siteId).run();await audit(env,row.user_id,"SITE_CONTEXT_CHANGED","ALLOWED",id,{siteId});return json({ok:true})}
 const integratedAdminResponse=await handleIntegratedAdminRequest(request,env,url);if(integratedAdminResponse)return integratedAdminResponse;
 const boardAccessResponse=await handleBoardAccessAdminRequest(request,env,url);if(boardAccessResponse)return boardAccessResponse;
 const issueResponse=await handleIssueRequest(request,env,url);if(issueResponse)return issueResponse;
 const workforceResponse=await handleWorkforceRequest(request,env,url);if(workforceResponse)return workforceResponse;
 const constructionInspectionResponse=await handleConstructionInspectionRequest(request,env,url);if(constructionInspectionResponse)return constructionInspectionResponse;
 const constructionResponse=await handleConstructionRequest(request,env,url);if(constructionResponse)return constructionResponse;
 const safetyResponse=await handleSafetyRequest(request,env,url);if(safetyResponse)return safetyResponse;
 const qualityResponse=await handleQualityRequest(request,env,url);if(qualityResponse)return qualityResponse;
 throw new ApiError(404,"NOT_FOUND","The requested API path was not found.");
 }catch(error){const normalized=!(error instanceof ApiError)&&String(error).includes("MEMBERSHIP_SITE_PURPOSE_CONFLICT")?new ApiError(403,"MEMBERSHIP_SITE_PURPOSE_CONFLICT","운영 현장 사용자와 내부 테스트 현장 사용자를 서로 섞을 수 없습니다."):error;if(env.APP_ENV==="integration"&&!(normalized instanceof ApiError))console.error("INTEGRATION_INTERNAL_ERROR",normalized);const apiError=normalized instanceof ApiError,status=apiError?normalized.status:500,code=apiError?normalized.code:"INTERNAL_ERROR",body={ok:false,error:code,message:apiError?normalized.message:"The request could not be processed.",requestId:id};if(apiError&&normalized.field)body.field=normalized.field;if(apiError&&normalized.details)body.details=normalized.details;return json(body,status)}}};
