import { concreteDecision } from "./weatherDecision.js";
const MODELS=["kma","ecmwf","gfs","jma"]; const WEEKDAYS=["일","월","화","수","목","금","토"];
const pad=n=>String(n).padStart(2,"0");
function dateObj(offset){const d=new Date(); d.setDate(d.getDate()+offset); return d;}
function isoDate(offset){return dateObj(offset).toISOString().slice(0,10)}
function dateLabel(offset){const d=dateObj(offset); return `${d.getMonth()+1}/${d.getDate()}`}
function weekdayLabel(offset){return `(${WEEKDAYS[dateObj(offset).getDay()]})`}
function rainValue(day,hour,model){const peak=day===0?15:(10+day*2)%24;const distance=Math.abs(hour-peak);const base=Math.max(0,7-distance*1.7);const daily=[1,.5,.9,.2,.7,.35][day]||.3;const mf={kma:.9,ecmwf:1.15,gfs:1,jma:.75}[model]||1;const night=hour<6||hour>21?.35:1;return +(Math.max(0,base*daily*mf*night)).toFixed(1)}
function consistencyScore(values){const max=Math.max(...values),min=Math.min(...values);if(max===0)return 5;const spread=max-min;if(spread<=.5)return 5;if(spread<=1.5)return 4;if(spread<=3)return 3;if(spread<=5)return 2;return 1}
function stars(n){return "★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
export function getSixDayHourlyWeather(){const rows=[];for(let day=0;day<6;day++){for(let hour=0;hour<24;hour++){const modelRain=Object.fromEntries(MODELS.map(m=>[m,rainValue(day,hour,m)]));const vals=Object.values(modelRain);const rain1h=Math.max(...vals);const avgRain1h=+(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1);const score=consistencyScore(vals);const temp=+(24+Math.sin((hour-7)/24*Math.PI)*9+day*.2).toFixed(1);const humidity=rain1h>0?82:68;const wind=+(3+(hour>=13&&hour<=17?4.5:0)+day*.2).toFixed(1);const apparent=+(temp+Math.max(0,humidity-60)*.08+Math.max(0,temp-30)*.7).toFixed(1);rows.push({day,date:isoDate(day),dateLabel:dateLabel(day),weekdayLabel:weekdayLabel(day),hour:pad(hour),temp,humidity,wind,apparent,rain1h,avgRain1h,modelRain,consistency:score,stars:stars(score)})}}return rows}
function buildAiOpinion(todayRows){const rainy=todayRows.filter(h=>h.rain1h>.1);if(!rainy.length)return ["오늘은 뚜렷한 강수 신호가 약합니다.","다만 최신 예보를 확인하면서 외부작업을 진행하세요.","콘크리트 타설 전에는 현장 바닥 고임수와 보양재 준비 상태를 확인하세요."];const start=rainy[0].hour,end=rainy[rainy.length-1].hour,peak=todayRows.reduce((a,b)=>a.rain1h>=b.rain1h?a:b);return [`오늘은 ${start}시부터 강수가 시작되어 ${peak.hour}시경 최대 ${peak.rain1h.toFixed(1)}mm가 예상됩니다.`,`${end}시 이후에는 강수가 대부분 약해질 것으로 보입니다.`,`오전 07~11시에 외부 작업을 진행하는 것이 가장 유리합니다.`,`콘크리트 타설은 오전 완료를 권장하며, 오후 강수 시간대는 피해주세요.`,`배수로 점검 및 자재 방수 조치를 사전에 확인하세요.`]}
function buildWorkWindow(rows){const safe=rows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17&&h.rain1h<2&&h.wind<8&&h.apparent<35);if(!safe.length)return "오늘 07~17시 중 명확한 안전 작업시간이 없습니다.";return `${safe[0].hour} ~ ${safe[safe.length-1].hour}시`}
export function getDemoWeatherSummary(){const hourly=getSixDayHourlyWeather();const todayRows=hourly.filter(h=>h.day===0);const todayWork=todayRows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17);const maxRain=Math.max(...todayWork.map(x=>x.rain1h)),maxWind=Math.max(...todayWork.map(x=>x.wind)),maxApparent=Math.max(...todayWork.map(x=>x.apparent));const decision=concreteDecision({maxRain,maxWind,maxApparent});const peakRain=todayWork.find(x=>x.rain1h===maxRain);return {sourceMode:"v9.3.1 demo · 6일 1시간 강수 기준",hourly,todayRows,maxRain,maxWind,maxApparent,peakHeat:todayWork.find(x=>x.apparent===maxApparent),peakRain,peakWind:todayWork.find(x=>x.wind===maxWind),concrete:decision,aiOpinion:buildAiOpinion(todayRows),todayConsistency:peakRain?.stars||"★★★★★",workWindow:buildWorkWindow(todayWork)}}
export function riskClass(level){if(level==="위험"||level==="danger"||level==="중지검토")return "risk-red";if(level==="주의"||level==="warning")return "risk-orange";if(level==="관찰"||level==="watch")return "risk-yellow";return "risk-blue"}
