import { concreteDecision } from "./weatherDecision.js";
const MODELS=["kma","ecmwf","gfs","jma"];
const WEEKDAYS=["일","월","화","수","목","금","토"];
function pad(n){return String(n).padStart(2,"0");}
function dateObj(offset){const d=new Date();d.setDate(d.getDate()+offset);return d;}
function dateLabel(offset){const d=dateObj(offset);return `${d.getMonth()+1}/${d.getDate()}`;}
function weekdayLabel(offset){return `(${WEEKDAYS[dateObj(offset).getDay()]})`;}
function isoDate(offset){return dateObj(offset).toISOString().slice(0,10);}
function rainValue(day,hour,model){const peak=day===0?15:(10+day*2)%24;const distance=Math.abs(hour-peak);const base=Math.max(0,7-distance*1.7);const dailyFactor=[1,.5,.9,.2,.7,.35][day]||.3;const modelFactor={kma:.9,ecmwf:1.15,gfs:1.0,jma:.75}[model]||1;const nightCut=hour<6||hour>21?.35:1;return +(Math.max(0,base*dailyFactor*modelFactor*nightCut)).toFixed(1);}
function consistencyFromValues(values){const max=Math.max(...values);const min=Math.min(...values);if(max===0)return 5;const spread=max-min;if(spread<=.5)return 5;if(spread<=1.5)return 4;if(spread<=3)return 3;if(spread<=5)return 2;return 1;}
function stars(n){return "★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n);}
export function getSixDayHourlyWeather(){const rows=[];for(let day=0;day<6;day++){for(let hour=0;hour<24;hour++){const modelRain=Object.fromEntries(MODELS.map(m=>[m,rainValue(day,hour,m)]));const values=Object.values(modelRain);const rain1h=Math.max(...values);const avgRain1h=+(values.reduce((a,b)=>a+b,0)/MODELS.length).toFixed(1);const consistency=consistencyFromValues(values);const temp=+(24+Math.sin((hour-7)/24*Math.PI)*9+day*.2).toFixed(1);const humidity=rain1h>0?82:68;const wind=+(3+(hour>=13&&hour<=17?4.5:0)+day*.2).toFixed(1);const apparent=+(temp+Math.max(0,humidity-60)*.08+Math.max(0,temp-30)*.7).toFixed(1);rows.push({day,date:isoDate(day),dateLabel:dateLabel(day),weekdayLabel:weekdayLabel(day),hour:pad(hour),temp,humidity,wind,apparent,rain1h,avgRain1h,modelRain,consistency,stars:stars(consistency)});}}return rows;}
function buildAiOpinion(todayRows){const rainy=todayRows.filter(h=>h.rain1h>.1);if(!rainy.length)return "오늘은 뚜렷한 강수 신호가 약합니다. 다만 최신 예보를 확인하면서 외부작업을 진행하세요.";const start=rainy[0].hour;const end=rainy[rainy.length-1].hour;const peak=todayRows.reduce((a,b)=>a.rain1h>=b.rain1h?a:b);const morningSafe=todayRows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=11&&h.rain1h<2).length>=3;const workText=morningSafe?"오전 작업이 비교적 유리합니다.":"오전에도 강수 변동 가능성이 있어 작업 전 재확인이 필요합니다.";return `오늘은 ${start}시부터 강수가 시작되어 ${peak.hour}시경 최대 ${peak.rain1h.toFixed(1)}mm가 예상되며, ${end}시 이후 약해질 것으로 보입니다. ${workText} 콘크리트 타설은 강수 시간대를 피하고 보양재와 배수로를 먼저 확인하세요.`;}
function buildWorkWindow(rows){const safe=rows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17&&h.rain1h<2&&h.wind<8&&h.apparent<35);if(!safe.length)return "오늘 07~17시 중 명확한 안전 작업시간이 없습니다.";return `${safe[0].hour}시~${safe[safe.length-1].hour}시 사이가 비교적 유리합니다.`;}
export function getDemoWeatherSummary(){const hourly=getSixDayHourlyWeather();const todayRows=hourly.filter(h=>h.day===0);const workHourly=hourly.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17);const todayWork=workHourly.filter(h=>h.day===0);const maxRain=Math.max(...todayWork.map(x=>x.rain1h));const maxWind=Math.max(...todayWork.map(x=>x.wind));const maxApparent=Math.max(...todayWork.map(x=>x.apparent));const decision=concreteDecision({maxRain,maxWind,maxApparent});const peakRain=todayWork.find(x=>x.rain1h===maxRain);return {sourceMode:"v9.3 demo · 6일 1시간 강수 기준",hourly,todayRows,workHourly,maxRain,maxWind,maxApparent,peakHeat:todayWork.find(x=>x.apparent===maxApparent),peakRain,peakWind:todayWork.find(x=>x.wind===maxWind),concrete:decision,aiOpinion:buildAiOpinion(todayRows),todayConsistency:peakRain?.stars||"★★★★★",todayConsistencyScore:peakRain?.consistency||5,workWindow:buildWorkWindow(todayWork)};}
export function riskClass(level){if(level==="위험"||level==="danger"||level==="중지검토")return "risk-red";if(level==="주의"||level==="warning")return "risk-orange";if(level==="관찰"||level==="watch")return "risk-yellow";return "risk-blue";}
