import { concreteDecision } from "./weatherDecision.js";
const MODELS=["kma","ecmwf","gfs","jma"]; const WEEKDAYS=["일","월","화","수","목","금","토"];
const pad=n=>String(n).padStart(2,"0");
function kstNow(){return new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Seoul"}))}
function dateObj(offset){const d=kstNow(); d.setDate(d.getDate()+offset); return d;}
function isoDate(offset){const d=dateObj(offset);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function dateLabel(offset){const d=dateObj(offset); return `${d.getMonth()+1}/${d.getDate()}`}
function weekdayLabel(offset){return `(${WEEKDAYS[dateObj(offset).getDay()]})`}
function baseTimeLabel(){const d=kstNow();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:00 (KST)`}
function rainValue(day,hour,model){const peak=day===0?15:(10+day*2)%24;const distance=Math.abs(hour-peak);const base=Math.max(0,7-distance*1.7);const daily=[1,.5,.9,.2,.7,.35][day]||.3;const mf={kma:.9,ecmwf:1.15,gfs:1,jma:.75}[model]||1;const night=hour<6||hour>21?.35:1;return +(Math.max(0,base*daily*mf*night)).toFixed(1)}
function consistencyScore(values){const max=Math.max(...values),min=Math.min(...values);if(max===0)return 5;const spread=max-min;if(spread<=.5)return 5;if(spread<=1.5)return 4;if(spread<=3)return 3;if(spread<=5)return 2;return 1}
function stars(n){return "★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
function tempDecision(t){if(t>=38)return {level:"위험",title:"폭염 작업중지 검토",text:"실외작업은 시간 조정이 필요합니다. 열사병 증상(어지러움·두통·구토·의식저하) 확인, 그늘 휴식, 냉수·전해질, 관리자 순회를 강화하세요."};if(t>=35)return {level:"주의",title:"온열질환 주의",text:"11~15시 실외작업을 줄이고 물·그늘·휴식 주기를 고정하세요. 신규·고령·기저질환 작업자는 별도 확인이 필요합니다."};if(t<=0)return {level:"주의",title:"한랭 작업 주의",text:"결빙·저체온·손발 감각저하를 확인하고 방한장구, 미끄럼 방지, 온수 휴식을 준비하세요."};return {level:"관찰",title:"온도 관찰",text:"온도 위험은 낮지만 시간대별 체감온도 변화와 작업자 수분 섭취를 확인하세요."}}
function windDecision(w){if(w>=14)return {level:"위험",title:"양중·고소작업 중지 검토",text:"크레인, 고소작업차, 외장·비계 작업은 중지 또는 연기 검토가 필요합니다. 순간풍속과 장비 제작사 기준을 함께 확인하세요."};if(w>=10)return {level:"주의",title:"풍속 주의",text:"신호수, 작업반경, 양중물 유도줄, 아웃트리거 받침판, 자재 비산 방지를 확인하세요."};if(w>=7)return {level:"관찰",title:"풍속 관찰",text:"가벼운 자재 비산과 양중 흔들림을 확인하고 오후 시간대 풍속 상승을 추적하세요."};return {level:"양호",title:"풍속 양호",text:"일반 작업은 가능하나 장비작업 전 현장 순간풍속을 별도로 확인하세요."}}
function indoorDecision(maxRain,maxApparent){if(maxApparent>=35)return "실내작업도 밀폐·고습 구간은 온열 부담이 큽니다. 환기, 선풍기, 휴식, 냉수 배치를 확인하세요.";if(maxRain>=2)return "강우 시간대에는 실내 자재 반입 동선, 계단·출입구 미끄럼, 누수 유입을 확인하세요.";return "실내작업은 비교적 안정적입니다. 환기, 조도, 분진, 통로 정리를 중심으로 관리하세요."}
function outdoorDecision(maxRain,maxWind,maxApparent,workWindow){const notes=[];if(maxRain>=5)notes.push("강우 피크 시간에는 토공, 방수, 외장, 타설, 양중 작업을 피하고 배수로·보양재를 먼저 확보하세요.");else if(maxRain>=1)notes.push("약한 비가 있어 미끄럼, 자재 방수, 전기공구 누전 관리가 필요합니다.");else notes.push("강수 영향은 낮아 외부작업은 가능하지만 최신 예보를 재확인하세요.");if(maxWind>=10)notes.push("풍속이 높아 크레인·고소·외장 작업은 신호수와 작업반경 통제가 필요합니다.");if(maxApparent>=35)notes.push("고온 시간대는 11~15시 작업강도를 낮추고 물·그늘·휴식을 고정하세요.");notes.push(`오늘 추천 작업창은 ${workWindow}입니다.`);return notes.join(" ")}
export function getSixDayHourlyWeather(){const rows=[];for(let day=0;day<6;day++){for(let hour=0;hour<24;hour++){const modelRain=Object.fromEntries(MODELS.map(m=>[m,rainValue(day,hour,m)]));const vals=Object.values(modelRain);const rain1h=Math.max(...vals);const avgRain1h=+(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1);const score=consistencyScore(vals);const temp=+(25+Math.sin((hour-7)/24*Math.PI)*10+day*.25).toFixed(1);const humidity=rain1h>0?82:68;const wind=+(3+(hour>=13&&hour<=17?4.5:0)+day*.25).toFixed(1);const apparent=+(temp+Math.max(0,humidity-60)*.08+Math.max(0,temp-30)*.7).toFixed(1);rows.push({day,date:isoDate(day),dateLabel:dateLabel(day),weekdayLabel:weekdayLabel(day),hour:pad(hour),temp,humidity,wind,apparent,rain1h,avgRain1h,modelRain,consistency:score,stars:stars(score),tempDecision:tempDecision(apparent),windDecision:windDecision(wind)})}}return rows}
function buildWorkWindow(rows){const safe=rows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17&&h.rain1h<2&&h.wind<8&&h.apparent<35);if(!safe.length)return "오늘 07~17시 중 명확한 안전 작업시간이 없습니다.";return `${safe[0].hour} ~ ${safe[safe.length-1].hour}시`}

function modelAgreementOpinion(summary){
  const score = summary.peakRain?.consistency || 0;
  const vals = Object.values(summary.peakRain?.modelRain || {});
  const avg = summary.peakRain?.avgRain1h ?? 0;
  const max = summary.peakRain?.rain1h ?? 0;
  const spread = vals.length ? Math.max(...vals) - Math.min(...vals) : 0;
  if(score >= 4) return `예보처 신뢰도 높음: 4개 예보처가 대체로 일치합니다. 오늘 강수 판단은 최대 ${max.toFixed(1)}mm 기준으로 봐도 무리가 적습니다.`;
  if(score === 3) return `예보처 신뢰도 보통: 일부 차이는 있으나 큰 흐름은 비슷합니다. 튀는 예보보다 4개 예보처 평균 ${avg.toFixed(1)}mm 안팎의 강수를 우선 기준으로 보세요.`;
  return `예보처 신뢰도 낮음: 한곳만 튀는 예보가 포함됐을 가능성이 있습니다. 최대값 ${max.toFixed(1)}mm만 보지 말고 예보처 평균 ${avg.toFixed(1)}mm와 편차 ${spread.toFixed(1)}mm를 같이 확인하세요.`;
}
function buildAiOpinion(todayRows,summary){const rainy=todayRows.filter(h=>h.rain1h>.1);const lines=[];if(rainy.length){const start=rainy[0].hour,end=rainy[rainy.length-1].hour,peak=summary.peakRain;lines.push(`강수: ${start}시부터 ${end}시까지 비 신호가 있으며 ${peak.hour}시경 최대 ${peak.rain1h.toFixed(1)}mm가 예상됩니다.`)}else lines.push("강수: 오늘은 뚜렷한 강수 신호가 약합니다.");lines.push(modelAgreementOpinion(summary));lines.push(`야외작업: ${outdoorDecision(summary.maxRain,summary.maxWind,summary.maxApparent,summary.workWindow)}`);lines.push(`실내작업: ${indoorDecision(summary.maxRain,summary.maxApparent)}`);lines.push(`풍속: ${summary.peakWind.hour}시 최대 ${summary.maxWind.toFixed(1)}m/s입니다. ${windDecision(summary.maxWind).text}`);lines.push(`온도: ${summary.peakHeat.hour}시 최고 체감 ${summary.maxApparent.toFixed(1)}℃입니다. ${tempDecision(summary.maxApparent).text}`);lines.push("관리자 활용: 이 판단은 이후 안전관리·공사관리·품질관리 탭에서 공종별 경고와 조치사항으로 재사용할 수 있도록 구성했습니다.");return lines}
export function getDemoWeatherSummary(){const hourly=getSixDayHourlyWeather();const todayRows=hourly.filter(h=>h.day===0);const todayWork=todayRows.filter(h=>Number(h.hour)>=7&&Number(h.hour)<=17);const maxRain=Math.max(...todayWork.map(x=>x.rain1h)),maxWind=Math.max(...todayWork.map(x=>x.wind)),maxApparent=Math.max(...todayWork.map(x=>x.apparent));const decision=concreteDecision({maxRain,maxWind,maxApparent});const peakRain=todayWork.find(x=>x.rain1h===maxRain);const peakWind=todayWork.find(x=>x.wind===maxWind);const peakHeat=todayWork.find(x=>x.apparent===maxApparent);const workWindow=buildWorkWindow(todayWork);const summary={sourceMode:"v9.3.6 demo · 강수/온도/풍속 의사결정 배치 기준",baseTimeLabel:baseTimeLabel(),hourly,todayRows,maxRain,maxWind,maxApparent,peakHeat,peakRain,peakWind,concrete:decision,todayConsistency:peakRain?.stars||"★★★★★",workWindow};summary.aiOpinion=buildAiOpinion(todayRows,summary);return summary}
export function riskClass(level){if(level==="위험"||level==="danger"||level==="중지검토")return "risk-red";if(level==="주의"||level==="warning")return "risk-orange";if(level==="관찰"||level==="watch")return "risk-yellow";return "risk-blue"}
